export default function () {
  const menu = [
    {
      name: "Каша овсяная с ягодами",
      portion_size: "250",
      unit: "гр",
      price: 240,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a0000018945249436a6619a461193cc860c/M_height",
      description:
        "Овсяная каша приготовлена на молоке . С ягодным топпингом, свежими ягодами и соусом из ягод.",
      category: "BRANCH BREAKFAST",
      id: 1,
      type: [],
    },
    {
      name: "БЛИНЫ НА МАНЕР КРЕП-СЮЗЕТТ С ФРУКТАМИ",
      portion_size: "250",
      unit: "гр",
      price: 220,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a000001894521b8d68cf5d6b371d3cefde2/M_height",
      description:
        "Блины приготовлены на манер креп зюзет. В апельсиновом соке с тростниковым сахаром, фруктами. Блюдо дополнено ванильным соусом.",
      category: "BRANCH BREAKFAST",
      id: 2,
      type: [],
    },
    {
      name: "Глазунья цезарь",
      portion_size: "250",
      unit: "гр",
      price: 180,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a000001894512041ea29ddccfc29a2eab8c/M_height",
      description:
        "Яичница из двух яиц с салатом а-ля цезарь с куриной грудкой обжаренной на гриле.",
      category: "BRANCH BREAKFAST",
      id: 3,
      type: [],
    },
    {
      name: "Омлет с овощами, луковым вареньем",
      portion_size: "350",
      price: 210,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a00000189451c5a7fa690ba3613bf631275/M_height",
      description:
        "Запеченный омлет с брокколи, томатами, картофелем. Сочетаем с луковым вареньем.",
      category: "BRANCH BREAKFAST",
      id: 4,
      type: [],
    },
    {
      name: "БЕНЕДИКТ С ЛОСОСЕМ, ТОМАТАМИ И АВОКАДО",
      portion_size: "330",
      unit: "гр",
      price: 440,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189452d9670987ffd55a2f239592a/M_height",
      description:
        "Бриошь с морковным муссом, яйцом пашот, соусом голландез, лососем слабой соли, авокадо и томатами черри .",
      category: "BRANCH BREAKFAST",
      id: 5,
      type: [],
    },
    {
      name: "Пончики с фруктовым тартаром",
      portion_size: "220",
      unit: "гр",
      price: 280,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a00000189451aeebcc5f80d57dcece54cc3/M_height",
      description:
        "Пончики с тартаром из яблока, груши, персика с ягодами и соусом кленовым",
      category: "BRANCH BREAKFAST",
      id: 6,
      type: [],
    },
    {
      name: "САЛАТ С ИМБИРНЫМ ЦЫПЛЕНКОМ, КИНОА И ТОМАТАМИ",
      portion_size: "140",
      unit: "гр",
      price: 170,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 7,
      type: [],
    },
    {
      name: "ЗЕЛЕНЫЙ САЛАТ С КИНОА",
      portion_size: "140",
      unit: "гр",
      price: 130,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 8,
      type: [],
    },
    {
      name: "КУРИНЫЙ СУП С ЛАПШОЙ",
      portion_size: "300",
      unit: "гр",
      price: 120,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 9,
      type: [],
    },
    {
      name: "СУП-ГУЛЯШ",
      portion_size: "300",
      unit: "гр",
      price: 180,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 10,
      type: [],
    },
    {
      name: "БЕФСТРОГАНОВ С КАРТОФЕЛЬНЫМ ПЮРЕ",
      portion_size: "300",
      unit: "гр",
      price: 240,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 11,
      type: [],
    },
    {
      name: "КОТЛЕТЫ ПОЖАРСКИЕ С КАРТОФЕЛЬНЫМ ПЮРЕ",
      portion_size: "290",
      unit: "гр",
      price: 190,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 12,
      type: [],
    },
    {
      name: "НАПИТОК ДНЯ (ЧАЙ, КОФЕ, МОРС)",
      portion_size: "200",
      unit: "мл",
      price: 75,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 13,
      type: [],
    },
    {
      name: "ДЕСЕРТ ДНЯ",
      portion_size: "1",
      unit: "шт",
      price: 100,
      image: "",
      description: "",
      category: "BRANCH BREAKFAST",
      id: 14,
      type: [],
    },
    {
      name: "эспрессо",
      portion_size: "38",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      category: "кофе",
      id: 15,
      type: [],
    },
    {
      name: "американо",
      portion_size: "300",
      unit: "мл",
      price: 120,
      image: "",
      description: "",
      category: "кофе",
      id: 16,
      type: [],
    },
    {
      name: "капучино",
      portion_size: "300",
      unit: "мл",
      price: 140,
      image: "",
      description: "",
      category: "кофе",
      id: 17,
      type: [],
    },
    {
      name: "флет уайт",
      portion_size: "300",
      unit: "мл",
      price: 160,
      image: "",
      description: "",
      category: "кофе",
      id: 18,
      type: [],
    },
    {
      name: "раф",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "кофе",
      id: 19,
      type: [],
    },
    {
      name: "капучино с лавандой",
      portion_size: "300",
      unit: "мл",
      price: 160,
      image: "",
      description: "",
      category: "кофе",
      id: 20,
      type: [],
    },
    {
      name: "кофе на банановом",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "кофе",
      id: 21,
      type: [],
    },
    {
      name: "кофе на кокосовом",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "кофе",
      id: 22,
      type: [],
    },
    {
      name: "капучино с малиной",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "кофе",
      id: 23,
      type: [],
    },
    {
      name: "банановый фраппе",
      portion_size: "350",
      unit: "мл",
      price: 170,
      image: "",
      description: "",
      category: "кофе",
      id: 24,
      type: [],
    },
    {
      name: "черный",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 25,
      type: [],
    },
    {
      name: "зеленый сенча",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 26,
      type: [],
    },
    {
      name: "зеленый дыня карамель",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 27,
      type: [],
    },
    {
      name: "пуэр юннань",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 28,
      type: [],
    },
    {
      name: "улун молочный",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 29,
      type: [],
    },
    {
      name: "дерзкий фрукт",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 30,
      type: [],
    },
    {
      name: "черный черная смородина",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 31,
      type: [],
    },
    {
      name: "черный эрл грей",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 32,
      type: [],
    },
    {
      name: "черный барбарисовый",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 33,
      type: [],
    },
    {
      name: "травяной лимон с имбирем",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 34,
      type: [],
    },
    {
      name: "травяной мятный каркаде",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      category: "чай",
      id: 35,
      type: [],
    },
    {
      name: "персик-розмарин",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      category: "фирменный чай",
      id: 36,
      type: [],
    },
    {
      name: "Лемонграсс-киви",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a00000189981c21180e5462c9793dda968f/M_height",
      description: "",
      category: "фирменный чай",
      id: 37,
      type: [],
    },
    {
      name: "черная смородина-каркаде",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a000001899818ff997bc6ac5a49c160cc56/M_height",
      description: "",
      category: "фирменный чай",
      id: 38,
      type: [],
    },
    {
      name: "Облепиха-Глинтвейн",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a00000189981b6202385e9e15fc07c6d874/M_height",
      description: "",
      category: "фирменный чай",
      id: 39,
      type: [],
    },
    {
      name: "ХЛЕБНЫЕ ПАЛОЧКИ С ЧЕСНОКОМ",
      portion_size: "120",
      unit: "гр",
      price: 210,
      image: "",
      description: "Готовятся с сыром пармезан, чесноком и соусом кимчи",
      category: "закуски",
      id: 40,
      type: [],
    },
    {
      name: "БАКЛАЖАНЫ С ТОМАТАМИ В КЛЕНОВОМ СОУСЕ",
      portion_size: "150",
      unit: "гр",
      price: 280,
      image: "",
      description:
        "Баклажаны, приготовленные во фритюре, с томатами, украшены лепестками миндаля",
      category: "закуски",
      id: 41,
      type: [],
    },
    {
      name: "СЫРНАЯ ТАРЕЛКА",
      portion_size: "290",
      unit: "гр",
      price: 650,
      image: "",
      description:
        "Изысканное сочетание сыров бри, пармезан, дорблю, качотта с трюфелем, подается с миндалем, грецким орехом и кешью. Дополнено финиками, виноградом и голубикой. Оттеняется топпингами: медом и малиновым вареньем",
      category: "закуски",
      id: 42,
      type: [],
    },
    {
      name: "ФРУКТОВАЯ ТАРЕЛКА",
      portion_size: "510",
      unit: "гр",
      price: 550,
      image: "",
      description: "",
      category: "закуски",
      id: 43,
      type: [],
    },
    {
      name: "ЖАРЕНЫЙ КАРТОФЕЛЬ СО СМЕТАНОЙ И ЩУЧЬЕЙ ИКРОЙ",
      portion_size: "230",
      unit: "гр",
      price: 280,
      image: "",
      description: "",
      category: "закуски",
      id: 44,
      type: [],
    },
    {
      name: "стрипсы из индейки с муссом из моркови",
      portion_size: "160/30/30",
      price: 260,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a000001894532f2993dae8b89b3d0b3b9c6/M_height",
      description: "",
      category: "закуски",
      id: 45,
      type: [],
    },
    {
      name: "Сэндвич BLT",
      portion_size: "300",
      price: 410,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189452bc4f74e11671c77521a641b/M_height",
      description:
        "Авторская бриошь от шефа с томатами, салатом, индейкой, приготовленной по технологии су-вид, авторским соусом, сыром гауда и беконом. Украшен чатни из яблок",
      category: "закуски",
      id: 46,
      type: [],
    },
    {
      name: "Сендвич Бан ми",
      portion_size: "250",
      price: 390,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a000001894537bc6867850e6d0625dd6b49/M_height",
      description:
        "Авторская бриошь от шефа с риетом из индейки, брискетом, свежей морковью, огурцами и салатом романо. Приправлен соусами пад-тай и кленовым",
      category: "закуски",
      id: 47,
      type: [],
    },
    {
      name: "Тартин с лососем, мягким сыром",
      portion_size: "170",
      price: 420,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189453a197992e919fd6d99e95388/M_height",
      description:
        "Хлеб тартин с авокадо, мягким сыром, томатами и слабосоленым лососем",
      category: "закуски",
      id: 48,
      type: [],
    },
    {
      name: "Тартар из говядины с хрустящими луковыми пирожками",
      portion_size: "250",
      price: 450,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a0000018945454a52c8b6deb90eae14e515/M_height",
      description: "",
      category: "закуски",
      id: 49,
      type: [],
    },
    {
      name: "Хлебная корзина",
      portion_size: "150",
      unit: "гр",
      price: 150,
      image: "",
      description: "",
      category: "закуски",
      id: 50,
      type: [],
    },
    {
      name: "КОЕ-КАКИЕ ОВОЩИ С РУБЛЕНЫМИ ОРЕХАМИ",
      portion_size: "180",
      unit: "гр",
      price: 250,
      image: "",
      description: "",
      category: "салаты",
      id: 51,
      type: [],
    },
    {
      name: "ПРЯНЫЙ СЫР С ФРУКТАМИ НА ЛИСТЬЯХ САЛАТА",
      portion_size: "160",
      unit: "гр",
      price: 240,
      image: "",
      description:
        "Листья салата с мягким сыром, грушей и консервированным персиком, обжаренными на углях в меду. Украшен специями сумах, заправляется соусом на основе оливкого масла",
      category: "салаты",
      id: 52,
      type: [],
    },
    {
      name: "АВТОРСКАЯ МИМОЗА С СОУСОМ МАЙО",
      portion_size: "270",
      unit: "гр",
      price: 280,
      image: "",
      description:
        "Авторское прочтение классического рецепта мимозы с риетом из двух видов рыбы с домашним майонезом и печеной свеклой",
      category: "салаты",
      id: 53,
      type: [],
    },
    {
      name: "САЛАТ С БРИСКЕТОМ ИЗ ПЕЧИ",
      portion_size: "220",
      unit: "гр",
      price: 380,
      image: "",
      description:
        "Говяжья грудинка с огурцом малой соли, запеченным болгарским перцем, листьями салата, свежим цукини и соусом пад тай. Украшен чатни из вишни и яблока",
      category: "салаты",
      id: 54,
      type: [],
    },
    {
      name: "ОЛИВЬЕ С БРИСКЕТОМ",
      portion_size: "230",
      unit: "гр",
      price: 260,
      image: "",
      description: "",
      category: "салаты",
      id: 56,
      type: [],
    },
    {
      name: "САЛАТ С АРОМАТНЫМ ФИЛЕ ЦЫПЛЕНКА И КЛЕНОВОИ ЗАПРАВКОЙ",
      portion_size: "210",
      unit: "гр",
      price: 360,
      image: "",
      description:
        "Микс салатов романо и шпината с томатами, свежим цукини и теплым филе цыпленка",
      category: "салаты",
      id: 57,
      type: [],
    },
    {
      name: "маргарита",
      portion_size: "440",
      unit: "гр",
      price: 490,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a00000189537a6893fc63308d95f91387d0/M_height",
      description: "",
      category: "пицца",
      id: 58,
      type: [],
    },
    {
      name: "ГРУША ДОР-БЛЮ",
      portion_size: "450",
      unit: "гр",
      price: 540,
      image: "",
      description: "",
      category: "пицца",
      id: 59,
      type: [],
    },
    {
      name: "4 сыра",
      portion_size: "455",
      unit: "гр",
      price: 520,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a000001895378b0233df6f1e8d9e215ffa1/M_height",
      description: "",
      category: "пицца",
      id: 60,
      type: [],
    },
    {
      name: "с пельменями",
      portion_size: "600",
      unit: "гр",
      price: 510,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a00000189537d67c06b674750de764f0fe0/M_height",
      description: "сметанный соус, пельмени, малосольные огурцы",
      category: "пицца",
      id: 61,
      type: [],
    },
    {
      name: "ВЕТЧИНА-ГРИБЫ",
      portion_size: "530",
      unit: "гр",
      price: 450,
      image: "",
      description: "",
      category: "пицца",
      id: 62,
      type: [],
    },
    {
      name: "С СОУСОМ РАНЧ И КУРИНЫМ БЕДРОМ",
      portion_size: "530",
      unit: "гр",
      price: 470,
      image: "",
      description: "",
      category: "пицца",
      id: 63,
      type: [],
    },
    {
      name: "пеперони",
      portion_size: "480",
      unit: "гр",
      price: 490,
      image: "",
      description: "томатный соус собственного производства, ломтики пеперони",
      category: "пицца",
      id: 64,
      type: [],
    },
    {
      name: "ПИККАНТЕ",
      portion_size: "550",
      unit: "гр",
      price: 520,
      image: "",
      description: "",
      category: "пицца",
      id: 65,
      type: [],
    },
    {
      name: "НАШИ ПИРОГИ ИЗ ПЕЧИ С КУРИННЫМ МЯСОМ",
      portion_size: "300/40",
      price: 450,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018953b0eb0d97f17e316f56959c50/M_height",
      description: "",
      category: "пироги",
      id: 66,
      type: [],
    },
    {
      name: "НАШИ ПИРОГИ ИЗ ПЕЧИ С ГовЯЖИм МЯСОМ",
      portion_size: "300/40",
      price: 450,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018953b0eb0d97f17e316f56959c50/M_height",
      description: "",
      category: "пироги",
      id: 67,
      type: [],
    },
    {
      name: "АВТОРСКИЙ ХАЧАПУРИ",
      portion_size: "380",
      unit: "гр",
      price: 420,
      image: "",
      description: "",
      category: "пироги",
      id: 68,
      type: [],
    },
    {
      name: "Тыквенный суп-крем",
      portion_size: "250",
      price: 280,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a00000189536a3712eb33d71508418ae380/M_height",
      description:
        "Сливочный суп украшен беконом, цукини и тыквенными семечками",
      category: "супы",
      id: 69,
      type: [],
    },
    {
      name: "Борщ с томленой грудинкой",
      portion_size: "380/40/20/20/5",
      price: 350,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018948a6699398def242aec442ce15/M_height",
      description: "",
      category: "супы",
      id: 70,
      type: [],
    },
    {
      name: "Уха на крепком бульоне",
      portion_size: "290",
      unit: "гр",
      price: 260,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a00000189535f7c41b317cbc4932bfdf57b/M_height",
      description: "",
      category: "супы",
      id: 71,
      type: [],
    },
    {
      name: "Просто вкусный куриный суп",
      portion_size: "360",
      price: 240,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a000001895372003d0aa8d88f5074a63c08/M_height",
      description: "",
      category: "супы",
      id: 72,
      type: [],
    },
    {
      name: "Суп с фрикадельками",
      portion_size: "260",
      unit: "гр",
      price: 220,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189536d6c2a8781678030800ea71a/M_height",
      description: "",
      category: "супы",
      id: 73,
      type: [],
    },
    {
      name: "арабьята",
      portion_size: "330",
      unit: "гр",
      price: 380,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a0000018953814ff67fbdad82d91c151508/M_height",
      description: "",
      category: "паста",
      id: 74,
      type: [],
    },
    {
      name: "сливочная с лососем и красной икрой",
      portion_size: "300",
      unit: "гр",
      price: 710,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953af45847459f124205890aec6/M_height",
      description: "",
      category: "паста",
      id: 75,
      type: [],
    },
    {
      name: "болоньезе с шашлыком",
      portion_size: "310",
      unit: "гр",
      price: 360,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a0000018953aca9a01e2fc59778a5bd8407/M_height",
      description: "",
      category: "паста",
      id: 76,
      type: [],
    },
    {
      name: "Карбонара без кое-каких сливок",
      portion_size: "290",
      unit: "гр",
      price: 340,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a0000018953ae4c85bd5b5aff0b53dd2e00/M_height",
      description: "",
      category: "паста",
      id: 77,
      type: [],
    },
    {
      name: "Пельмени классические",
      portion_size: "350",
      unit: "гр",
      price: 240,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953b8a4e6cf7a9382641f9b50b0/M_height",
      description: "",
      category: "горячее",
      id: 78,
      type: [],
    },
    {
      name: "Пельмени куриные",
      portion_size: "300",
      unit: "гр",
      price: 220,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953b8a4e6cf7a9382641f9b50b0/M_height",
      description: "",
      category: "горячее",
      id: 79,
      type: [],
    },
    {
      name: "Порубленные Куриные котлеты с картофельным пюре",
      portion_size: "320",
      price: 450,
      unit: "гр",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953c465870252358658d44ca61f/M_height",
      description: "",
      category: "горячее",
      id: 80,
      type: [],
    },
    {
      name: "Бифштекс с пшенной кашей из детства",
      portion_size: "330",
      unit: "гр",
      price: 400,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953c4d43b7e48a798120c7f4853/M_height",
      description: "",
      category: "горячее",
      id: 81,
      type: [],
    },
    {
      name: "ПЕЧЕННЫЙ НА УГЛЯХ КАРТОФЕЛЬ С ТОМЛЕНЫМ МЯСОМ",
      portion_size: "350",
      unit: "гр",
      price: 520,
      image: "",
      description: "",
      category: "горячее",
      id: 82,
      type: [],
    },
    {
      name: "ЧЕТВЕРТЬ ЦЫПЛЕНКА В ЛАВАШЕ",
      portion_size: "400",
      unit: "гр",
      price: 530,
      image: "",
      description:
        "Цыпленок, приготовленный на углях, с овощами и томатным соусом в лаваше",
      category: "горячее",
      id: 83,
      type: [],
    },
    {
      name: "СТЕЙК ИЗ НЕГОРБУШИ",
      portion_size: "260",
      unit: "гр",
      price: 790,
      image: "",
      description:
        "Рыба семейства лососевых, подается на подушке из кус-куса с овощами, семенами тыквы и подсолнечника",
      category: "горячее",
      id: 84,
      type: [],
    },
    {
      name: "ЛОПАТКА ГОВЯЖЬЯ С ОВОЩАМИ",
      portion_size: "180/150/50",
      unit: "гр",
      price: 820,
      image: "",
      description:
        "Стейк топ-блейд, беби-картофель и морковь. Украшен чатни из вишни и микрозеленью",
      category: "горячее",
      id: 85,
      type: [],
    },
    {
      name: "Манговый медовик",
      portion_size: "150",
      unit: "гр",
      price: 220,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d97aa4abfd34ccb3616963a0/M_height",
      description:
        "Пропитанные медовые коржи в сочетании со сметанным кремом и прослойкой из мангового пюре. Украшен ягодами голубики.",
      category: "десерты",
      id: 86,
      type: [],
    },
    {
      name: "Наполеон малиновый",
      portion_size: "150",
      unit: "гр",
      price: 220,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018953d811db09cfb11ef9c53c6d06/M_height",
      description:
        "Слоеное тесто собственного производства в сочетании с заварным кремом и прослойкой из малинового соуса.",
      category: "десерты",
      id: 87,
      type: [],
    },
    {
      name: "МЕРЕНГОВЫЙ РУЛЕТ С МАНГО",
      portion_size: "160",
      unit: "гр",
      price: 230,
      image: "",
      description:
        "Основа - нежная хрустящая меренга с крем-чизом и манговой прослойкой. Украшен мятой и свежей клубникой",
      category: "десерты",
      id: 88,
      type: [],
    },
    {
      name: "ТОРТ ЭСТЕРХАЗИ",
      portion_size: "160",
      unit: "гр",
      price: 260,
      image: "",
      description:
        "Фундучный бисквит выпекается без муки, с молочно-карамельной начинкой, украшен грецким орехом и лепестками миндаля",
      category: "десерты",
      id: 89,
      type: [],
    },
    {
      name: "ТОРТ КРАСНЫЙ БАРХАТ",
      portion_size: "130",
      unit: "гр",
      price: 220,
      image: "",
      description: "Красный бисквит с начинкой крем-чиза и клубники",
      category: "десерты",
      id: 90,
      type: [],
    },
    {
      name: "ТОРТ МАКОВЫЙ С ЛИМОНОМ",
      portion_size: "150",
      unit: "гр",
      price: 260,
      image: "",
      description:
        "Маковый нежный бисквит с ванильным крем-чизом и лимонным курдом",
      category: "десерты",
      id: 91,
      type: [],
    },
    {
      name: "ТОРТ ШОКОЛАДНО-БАНАНОВЫЙ",
      portion_size: "145",
      unit: "гр",
      price: 220,
      image: "",
      description:
        "Шоколадный, сочный бисквит с крем-чизом и нежной банановой прослойкой",
      category: "десерты",
      id: 92,
      type: [],
    },
    {
      name: "ТОРТ СНИКЕРС",
      portion_size: "150",
      unit: "гр",
      price: 220,
      image: "",
      description:
        "Шоколадный бисквит со сливочно-сырным кремом, солёной карамелью и арахисом",
      category: "десерты",
      id: 93,
      type: [],
    },
    {
      name: "ЧИЗКЕЙК С ЯГОДНЫМ СОУСОМ",
      portion_size: "150",
      unit: "гр",
      price: 280,
      image: "",
      description:
        "Классический чизкейк на корже из песочного теста. Подается с ягодным соусом",
      category: "десерты",
      id: 94,
      type: [],
    },
    {
      name: "ШОКОЛАДНЫЙ ЧИЗ",
      portion_size: "150",
      unit: "гр",
      price: 285,
      image: "",
      description:
        "Классический чизкейк с добавлением шоколада на корже из песочного теста. Украшен шоколадной крошкой",
      category: "десерты",
      id: 95,
      type: [],
    },
    {
      name: "КЕЙК-ПОП",
      portion_size: "50",
      unit: "гр",
      price: 80,
      image: "",
      description:
        "Классическое пирожное «Картошка» с подачей в форме кейк-попа в шоколадной глазури",
      category: "десерты",
      id: 96,
      type: [],
    },
    {
      name: "КАПКЕЙК БАНАН",
      portion_size: "100/65/105",
      unit: "гр",
      price: 100,
      image: "",
      description: "Шоколадный бисквит с начинкой, украшен шапкой из крем-чиза",
      category: "десерты",
      id: 97,
      type: [],
    },
    {
      name: "КАПКЕЙК МАЛИНА",
      portion_size: "100/65/105",
      unit: "гр",
      price: 110,
      image: "",
      description: "Шоколадный бисквит с начинкой, украшен шапкой из крем-чиза",
      category: "десерты",
      id: 98,
      type: [],
    },
    {
      name: "КАПКЕЙК СОЛЕНАЯ КАРАМЕЛЬ",
      portion_size: "100/65/105",
      unit: "гр",
      price: 100,
      image: "",
      description: "Шоколадный бисквит с начинкой, украшен шапкой из крем-чиза",
      category: "десерты",
      id: 99,
      type: [],
    },
    {
      name: "Картофель фри",
      portion_size: "150",
      unit: "гр",
      price: 180,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d69b92396bfb584c5736a7a2/M_height",
      description: "",
      category: "гарнир",
      id: 100,
      type: [],
    },
    {
      name: "Картофельное пюре",
      portion_size: "150",
      unit: "гр",
      price: 170,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d2183a2b780558d530a4c836/M_height",
      description: "",
      category: "гарнир",
      id: 101,
      type: [],
    },
    {
      name: "Овощи на пару",
      portion_size: "150",
      unit: "гр",
      price: 120,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d61427670ad5293d33cf235b/M_height",
      description: "",
      category: "гарнир",
      id: 102,
      type: [],
    },
    {
      name: "Овощи на гриле",
      portion_size: "150",
      unit: "гр",
      price: 160,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953b24b40c912f63cd57a2736ec/M_height",
      description: "",
      category: "гарнир",
      id: 103,
      type: [],
    },
    {
      name: "Рис отварной",
      portion_size: "150",
      unit: "гр",
      price: 100,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a0000018953d35911ce8b94a0878fef7e1c/M_height",
      description: "",
      category: "гарнир",
      id: 104,
      type: [],
    },
    {
      name: "ШАШЛЫК ИЗ СВИНОЙ ШЕИ",
      portion_size: "180/40/40",
      unit: "гр",
      price: 380,
      image: "",
      description: "",
      category: "на углях",
      id: 105,
      type: [],
    },
    {
      name: "ШАШЛЫК ИЗ КУРИНОГО БЕДРА",
      portion_size: "180/40/40",
      unit: "гр",
      price: 340,
      image: "",
      description: "",
      category: "на углях",
      id: 106,
      type: [],
    },
    {
      name: "ЛЮЛЯ-КЕБАБ ИЗ ГОВЯДИНЫ И БАРАНИНЫ",
      portion_size: "150/40/40",
      unit: "гр",
      price: 450,
      image: "",
      description: "",
      category: "на углях",
      id: 107,
      type: [],
    },
    {
      name: "КУПАТЫ ИЗ СВИНИНЫ",
      portion_size: "150/40/40",
      unit: "гр",
      price: 290,
      image: "",
      description: "",
      category: "на углях",
      id: 108,
      type: [],
    },
    {
      name: "КУПАТЫ ДОМАШНИЕ",
      portion_size: "150/40/40",
      unit: "гр",
      price: 320,
      image: "",
      description: "",
      category: "на углях",
      id: 109,
      type: [],
    },
    {
      name: "бон аква газ",
      portion_size: "330",
      unit: "мл",
      price: 120,
      image: "",
      description: "",
      category: "напитки",
      id: 110,
      type: [],
    },
    {
      name: "бон аква негаз",
      portion_size: "330",
      unit: "мл",
      price: 120,
      image: "",
      description: "",
      category: "напитки",
      id: 111,
      type: [],
    },
    {
      name: "рич ананас",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "напитки",
      id: 112,
      type: [],
    },
    {
      name: "рич апельсин",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "напитки",
      id: 113,
      type: [],
    },
    {
      name: "рич яблоко",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "напитки",
      id: 114,
      type: [],
    },
    {
      name: "рич вишня",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "напитки",
      id: 115,
      type: [],
    },
    {
      name: "рич персик",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "напитки",
      id: 116,
      type: [],
    },
    {
      name: "рич томат",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      category: "напитки",
      id: 117,
      type: [],
    },
    {
      name: "добрый кола",
      portion_size: "330",
      unit: "мл",
      price: 140,
      image: "",
      description: "",
      category: "напитки",
      id: 118,
      type: [],
    },
    {
      name: "Классический",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018997c773ba69e5dbb954266598da/M_height",
      description:
        "Сахарный сироп Сок лимона  Содовая Мята очищенная Лимон очищеный",
      category: "лимонады",
      id: 119,
      type: [],
    },
    {
      name: "Тархун",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018997c99b5bd00075391791cc2745/M_height",
      description: "Сироп тархун Сок лимона Содовая Лимон очищенный Лёд",
      category: "лимонады",
      id: 120,
      type: [],
    },
    {
      name: "Огурец-мята",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018997bac77d409d7e24919c7015e4/M_height",
      description:
        "Огурец свежий Сок лимона Сахарный сироп Содовая Мята очищенная Лёд",
      category: "лимонады",
      id: 121,
      type: [],
    },
    {
      name: "маракуя-матча",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      category: "лимонады",
      id: 122,
      type: [],
    },
    {
      name: "Малина-клубника-огурец",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018997c7fb417ad2b9a7a501f5ae7d/M_height",
      description:
        "Сироп Малина Сироп Клубника Сироп Миндаль Огурец свежий Сок лимона Содовая  Лёд",
      category: "лимонады",
      id: 123,
      type: [],
    },
    {
      name: "Груша-базилик",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a0000018997b09d8e14bcc2fd3dbdf725bb/M_height",
      description:
        "Сироп Груша  Базилик свежий очищенный Сок лимона  Содовая Лёд",
      category: "лимонады",
      id: 124,
      type: [],
    },
    {
      name: "Облепиха тархун",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a0000018997b5ab275ac77d2cce7fea5937/M_height",
      description:
        "Сироп Облепиха  Сироп тархун Сок лимона  Содовая Апельсин неочищенный Лёд",
      category: "лимонады",
      id: 125,
      type: [],
    },
    {
      name: "Груша-Щавель",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018997bed5ab7dfa9d5906cd8eedd0/M_height",
      description: "Сироп Груша Сироп Жвачка Сок лимона Щавель Содовая Лёд",
      category: "лимонады",
      id: 126,
      type: [],
    },
    {
      name: "Грейпфрут-бабл гам",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a00000189979a97d6ff5734cd945805566b/M_height",
      description:
        "Грейпфрутовый сок Сироп Сок лимона Содовая Лайм неочищенный Лёд",
      category: "лимонады",
      id: 127,
      type: [],
    },
    {
      name: "Лаванда-малина",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018997a0fbd928177c090811bea13a/M_height",
      description:
        "Сироп Лаванда Сироп Малина  Сок лимона  Содовая Апельсин неочищенный Лёд",
      category: "лимонады",
      id: 128,
      type: [],
    },
    {
      name: "Ананас-миндаль",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018997a41451f801db1c8569ca1b9d/M_height",
      description:
        "Ананасовый сок Сахарный сироп Сироп Миндаль Сок лимона Содовая Мята очищенная Лайм неочищенный Лёд",
      category: "лимонады",
      id: 129,
      type: [],
    },
    {
      name: "ягодный лемонграсс",
      portion_size: "250",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      category: "морсы",
      id: 130,
      type: [],
    },
    {
      name: "клюква-имбирь",
      portion_size: "250",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      category: "морсы",
      id: 131,
      type: [],
    },
    {
      name: "облепиха-вишня",
      portion_size: "250",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      category: "морсы",
      id: 132,
      type: [],
    },
    {
      name: "киви",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a0000018954466f579c74945b8d497da518/M_height",
      description: "",
      category: "милкшейки",
      id: 133,
      type: [],
    },
    {
      name: "банановый с шоколадом",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a0000018954466f579c74945b8d497da518/M_height",
      description: "",
      category: "милкшейки",
      id: 134,
      type: [],
    },
    {
      name: "классика",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a0000018954466f579c74945b8d497da518/M_height",
      description: "",
      category: "милкшейки",
      id: 135,
      type: [],
    },
    {
      name: "карамельный",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a0000018954466f579c74945b8d497da518/M_height",
      description: "",
      category: "милкшейки",
      id: 136,
      type: [],
    },

    {
      name: "КАВИРО АГРИКОЛА ПИНО ГРИДЖИО",
      portion_size: "750",
      unit: "мл",
      price: 2100,
      image: "",
      type: ["Сухое"],
      category: "БЕЛЫЕ ВИНА",
      description: "",
      id: 1000,
    },
    {
      name: "РИСЛИНГ БЕКШТАЙНЕР",
      portion_size: "750",
      unit: "мл",
      price: 2250,
      image: "",
      type: ["Сухое"],
      category: "БЕЛЫЕ ВИНА",
      description: "",
      id: 1001,
    },
    {
      name: "АРКО БЭЙ МАЛЬБОРО СОВИНЬОН БЛАН",
      portion_size: "750",
      unit: "мл",
      price: 2950,
      image: "",
      type: ["Сухое"],
      category: "БЕЛЫЕ ВИНА",
      description: "",
      id: 1002,
    },
    {
      name: "РИВЕР РУТ ГЕВЮРЦТРАМИНЕР",
      portion_size: "750",
      unit: "мл",
      price: 1850,
      image: "",
      type: ["Полусладкое"],
      category: "БЕЛЫЕ ВИНА",
      description: "",
      id: 1003,
    },
    {
      name: "ВИНЬЮ ВЕРДЕ АЛЬТУ ЛИМА",
      portion_size: "750",
      unit: "мл",
      price: 1600,
      image: "",
      type: ["Полусладкое"],
      category: "БЕЛЫЕ ВИНА",
      description: "",
      id: 1004,
    },
    {
      name: "ХАНС БАЕР РИСЛИН",
      portion_size: "750",
      unit: "мл",
      price: 2000,
      image: "",
      type: ["Сухое", "Безалкогольное"],
      category: "БЕЛЫЕ ВИНА",
      description: "",
      id: 1005,
    },
    {
      name: "КАМПО ДЕЛИЯ ЛА МАНЧА ТЕМПРАНИЛЬО",
      portion_size: "750",
      unit: "мл",
      price: 1750,
      image: "",
      type: ["Сухое"],
      category: "КРАСНЫЕ ВИНА",
      description: "",
      id: 1006,
    },
    {
      name: "ГАТО НЕГРО СЕМИСВИТ РЕД КАБЕРНЕ СОВИНЬОН",
      portion_size: "750",
      unit: "мл",
      price: 2450,
      image: "",
      type: ["Полусладкое"],
      category: "КРАСНЫЕ ВИНА",
      description: "",
      id: 1007,
    },
    {
      name: "ТРАПИЧЕ ВИНЬЯРДС МАЛЬБЕК",
      portion_size: "750",
      unit: "мл",
      price: 2200,
      image: "",
      type: ["Сухое"],
      category: "КРАСНЫЕ ВИНА",
      description: "",
      id: 1008,
    },
    {
      name: "КУКАБАРА КАБЕРНЕ СОВИНЬОН",
      portion_size: "750",
      unit: "мл",
      price: 1490,
      image: "",
      type: ["Полусухое"],
      category: "КРАСНЫЕ ВИНА",
      description: "",
      id: 1009,
    },
    {
      name: "ТОРНБЕРРИС ЗИНФАНДЕЛЬ РОЗЕ",
      portion_size: "750",
      unit: "мл",
      price: 1950,
      image: "",
      type: ["Полусладкое"],
      category: "РОЗОВЫЕ ВИНА",
      description: "",
      id: 1010,
    },
    {
      name: "ВАЙНКЕЛЛЕРАЙ ЛЕНЦ МОЗЕР ЦВАЙГЕЛЬТ РОЗЕ",
      portion_size: "750",
      unit: "мл",
      price: 1950,
      image: "",
      type: ["Сухое"],
      category: "РОЗОВЫЕ ВИНА",
      description: "",
      id: 1011,
    },
    {
      name: "ХАНС БАЕР ПИНО НУАР",
      portion_size: "750",
      unit: "мл",
      price: 2000,
      image: "",
      type: ["Полусладкре", "Безалкогольное"],
      category: "РОЗОВЫЕ ВИНА",
      description: "",
      id: 1012,
    },
    {
      name: "ПАВАО РОЗЕ",
      portion_size: "750",
      unit: "мл",
      price: 1600,
      image: "",
      type: ["Полусухое"],
      category: "РОЗОВЫЕ ВИНА",
      description: "",
      id: 1013,
    },
    {
      name: "ПРОСЕККО",
      portion_size: "750",
      unit: "мл",
      price: 3200,
      image: "",
      type: ["Сухое"],
      category: "ИГРИСТЫЕ ВИНА",
      description: "",
      id: 1014,
    },
    {
      name: "КАВА ВИНАРТ БРЮТ",
      portion_size: "750",
      unit: "мл",
      price: 2200,
      image: "",
      type: ["Сухое"],
      category: "ИГРИСТЫЕ ВИНА",
      description: "",
      id: 1015,
    },
    {
      name: "ГАЭТАНО АСТИ",
      portion_size: "750",
      unit: "мл",
      price: 1950,
      image: "",
      type: ["Сладкое"],
      category: "ИГРИСТЫЕ ВИНА",
      description: "",
      id: 1016,
    },
    {
      name: "ПТИ РОЗЕ",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      type: ["Белое", "Сухое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1017,
    },
    {
      name: "ГАЭТАНО ПИНОГРИДЖИО",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      type: ["Белое", "Полусухое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1018,
    },
    {
      name: "ФАЛЬКЕГБУРГ МУСКАТ",
      portion_size: "150",
      unit: "мл",
      price: 340,
      image: "",
      type: ["Белое", "Полусладкое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1019,
    },
    {
      name: "ПТИ РОЗЕ",
      portion_size: "150",
      unit: "мл",
      price: 285,
      image: "",
      type: ["Красное", "Сухое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1020,
    },
    {
      name: "ГАЭТАНО САНДЖОВЕЗ",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      type: ["Красное", "Полусухое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1021,
    },
    {
      name: "КАСА НЕРИ ТЕМПРАНИЛЬО",
      portion_size: "150",
      unit: "мл",
      price: 285,
      image: "",
      type: ["Красное", "Полусладкое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1022,
    },
    {
      name: "ВЫСОКИЙ БЕРЕГ ОРДИНАРНОЕ",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      type: ["Розовое", "Сухое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1023,
    },
    {
      name: "ГАЭТАНО ПРОСЕККО",
      portion_size: "150",
      unit: "мл",
      price: 420,
      image: "",
      type: ["Игристое", "Сухое"],
      category: "ВИНА ПО БОКАЛАМ",
      description: "",
      id: 1024,
    },
    {
      name: "ФЛЮГЕР",
      portion_size: "500",
      unit: "мл",
      price: 250,
      image: "",
      type: ["Светлое", "Фильтрованное"],
      category: "ПИВО",
      description: "",
      id: 1025,
    },
    {
      name: "КРЮГЕР ПИЛСНЕР",
      portion_size: "500",
      unit: "мл",
      price: 250,
      image: "",
      type: ["Светлое", "Фильтрованное"],
      category: "ПИВО",
      description: "",
      id: 1026,
    },
    {
      name: "КРЮГЕР ДУНКЕЛЬ",
      portion_size: "500",
      unit: "мл",
      price: 250,
      image: "",
      type: ["Темное", "Фильтрованное"],
      category: "ПИВО",
      description: "",
      id: 1027,
    },
    {
      name: "ХАРВЕСТЕР",
      portion_size: "500",
      unit: "мл",
      price: 250,
      image: "",
      type: ["Светлое", "Нефильтрованное"],
      category: "ПИВО",
      description: "",
      id: 1028,
    },
    {
      name: "БАКАЛАР",
      portion_size: "330",
      unit: "мл",
      price: 295,
      image: "",
      type: ["Светлое", "Фильтрованное", "Безалкогольное"],
      category: "ПИВО",
      description: "",
      id: 1029,
    },
    {
      name: "АРКОБРОЙ МОЗЕР ЛИЗЕЛЬ",
      portion_size: "500",
      unit: "мл",
      price: 490,
      image: "",
      type: ["Светлое", "Фильтрованное"],
      category: "ПИВО",
      description: "",
      id: 1030,
    },
    {
      name: "ЛИБЕНВАЙС ХЕФЕ-ВАЙСБИР",
      portion_size: "500",
      unit: "мл",
      price: 480,
      image: "",
      type: ["Светлое", "Нефильтрованное"],
      category: "ПИВО",
      description: "",
      id: 1031,
    },
    {
      name: "ЧЕРНОВАР",
      portion_size: "500",
      unit: "мл",
      price: 480,
      image: "",
      type: ["Темное", "Фильтрованное"],
      category: "ПИВО",
      description: "",
      id: 1032,
    },
    {
      name: "АПЕРОЛЬ АЛКО",
      portion_size: "200",
      unit: "мл",
      price: 310,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1033,
    },
    {
      name: "МИМОЗА",
      portion_size: "300",
      unit: "мл",
      price: 280,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1034,
    },
    {
      name: "КИР РОЯЛЬ",
      portion_size: "200",
      unit: "мл",
      price: 290,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1035,
    },
    {
      name: "КЛУБНИЧНЫЙ САУЕР",
      portion_size: "200",
      unit: "мл",
      price: 290,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1036,
    },
    {
      name: "ЧЕРНОСМОРОДИНОВЫЙ САУЕР",
      portion_size: "200",
      unit: "мл",
      price: 310,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1037,
    },
    {
      name: "МАНДАРИН РОЯЛЬ",
      portion_size: "200",
      unit: "мл",
      price: 310,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1038,
    },
    {
      name: "ФИЕРО ТОНИК",
      portion_size: "200",
      unit: "мл",
      price: 310,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1039,
    },
    {
      name: "БЕЛИНИ",
      portion_size: "200",
      unit: "мл",
      price: 310,
      image: "",
      type: [],
      category: "КОКТЕЙЛИ АЛКОГОЛЬНЫЕ",
      description: "",
      id: 1040,
    },
    {
      name: "ПЕРСИКОВЫЙ",
      portion_size: "300",
      unit: "мл",
      price: 220,
      image: "",
      type: [],
      description: "Персиковый сироп, пюре манго, сок лимона, кугарден 0%",
      category: "КОКТЕЙЛИ Б/А",
      id: 1041,
    },
    {
      name: "ГРУШЕВЫЙ",
      portion_size: "300",
      unit: "мл",
      price: 220,
      image: "",
      type: [],
      description:
        "Кленовый сироп, грушевый сироп, сок лимона, вино б/а, хугарден 0%",
      category: "КОКТЕЙЛИ Б/А",
      id: 1042,
    },
    {
      name: "АПЕРОЛЬ",
      portion_size: "300",
      unit: "мл",
      price: 200,
      image: "",
      type: [],
      description: "Сиропапероль, вино Б/А",
      category: "КОКТЕЙЛИ Б/А",
      id: 1043,
    },
    {
      name: "МОХИТО",
      portion_size: "300",
      unit: "мл",
      price: 200,
      image: "",
      type: [],
      description: "Сахарный сироп, лайм, мята, содовая",
      category: "КОКТЕЙЛИ Б/А",
      id: 1044,
    },
    {
      name: "МАНДАРИН-ТАРХУН",
      portion_size: "300",
      unit: "мл",
      price: 190,
      image: "",
      type: [],
      description:
        "Мандарин неочищенный, сироп тархун, сок лимона, Бон Аква газированная",
      category: "КОКТЕЙЛИ Б/А",
      id: 1045,
    },
    {
      name: "КУРАСАО",
      portion_size: "300",
      unit: "мл",
      price: 200,
      image: "",
      type: [],
      description:
        "Сок апельсина, сок ананаса, сок яблока, сироп блю курасао, сок лимона",
      category: "КОКТЕЙЛИ Б/А",
      id: 1046,
    },
    {
      name: "ГЛИНТВЕЙН",
      portion_size: "300",
      unit: "мл",
      price: 230,
      image: "",
      type: [],
      description: "Сок вишня/яблоко, апельсин, лимон, мед, яблоко, специи",
      category: "КОКТЕЙЛИ Б/А",
      id: 1047,
    },
  ];

  return {
    menu,
  };
}
