export default function () {
  const menu: Dish[] = [
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Хлебные палочки с чесноком",
      description: "С ссыром пармезан, чесноком и соусом кимчи",
      unit: 120,
      price: 210,
      feature: null,
      image: "",
      _id: 1,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Баклажаны с томатами в кленовом соусе",
      description:
        "Баклажаны приготовленные во фритюре, с томатами, украшен лепестками миндаля",
      unit: 150,
      price: 280,
      feature: null,
      image: "",
      _id: 2,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Сырная тарелка",
      description:
        "Изысканное сочетание сыров Бри, Памезан, Дор-блю, Качотта с трюфелем, подается с миндалем, грецким орехом и кешью. Дополнено финиками, виноградом и голубикой. Оттеняется топпингами: мед и малиновое варенье.",
      unit: 290,
      price: 690,
      feature: null,
      image: "",
      _id: 3,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Фруктовая тарелка",
      description: "Из сезонных фруктов",
      unit: 510,
      price: 650,
      feature: null,
      image: "",
      _id: 4,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Жареный картофель со сметаной и икрой палтуса",
      description: "-",
      unit: 230,
      price: 280,
      feature: null,
      image: "",
      _id: 5,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Стрипсы из индейки с муссом из моркови",
      description: "-",
      unit: "160/30/30",
      price: 260,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a000001894532f2993dae8b89b3d0b3b9c6/M_height",
      _id: 6,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Сэндвич BLT",
      description:
        "Авторская бриошь от шефа с томатами, салатом, индейкой приготовленной по технологии сувид, авторским соусом, сыром гауда и беконом. Украше чатни из яблок",
      unit: 300,
      price: 410,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189452bc4f74e11671c77521a641b/M_height",
      _id: 7,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Тартин с лососем, мягким сыром",
      description:
        "Хлеб тартин с авокадо, мягким сыром, томатами и слабосоленым лососем",
      unit: 170,
      price: 420,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189453a197992e919fd6d99e95388/M_height",
      _id: 8,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Тартар из говядины с  луковыми пирожками",
      description: "-",
      unit: 250,
      price: 450,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a0000018945454a52c8b6deb90eae14e515/M_height",
      _id: 9,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa60907d1b9558d226be9",
      name: "Хлебная корзина",
      description: null,
      unit: "245/320",
      price: 75,
      feature: null,
      image: "",
      _id: 10,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa61407d1b9558d226bec",
      name: "Кое-какие овощи с рублеными орехами\n",
      description:
        "Салат из свежих овощей с мелко порубленными орехами, подается с лепестками миндаля и микрозеленью",
      unit: 180,
      price: 270,
      feature: null,
      image: "",
      _id: 11,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa61407d1b9558d226bec",
      name: "Пряный сыр с фруктами гриль на листьях салата",
      description:
        "Мягкий творожный сыр со специями сумах. Подается с листьями салата, грушей, персиком обжаренным на углях",
      unit: 160,
      price: 260,
      feature: null,
      image: "",
      _id: 12,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa61407d1b9558d226bec",
      name: "Авторская мимоза с соусом майо",
      description:
        "Авторское прочтение классического рецепта мимозы с нежнейшим риетом из двух видов рыбы с домашним майонезом и печеной свеклой",
      unit: 270,
      price: 310,
      feature: null,
      image: "",
      _id: 13,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa61407d1b9558d226bec",
      name: "Салат с брискетом из печи",
      description:
        "Говяжья грудинка с огурцом малой соли, запеченым болгарским перцем, листьями салата, цукини под соусом пад-тай с чатни из вишни и яблок.",
      unit: 220,
      price: 390,
      feature: null,
      image: "",
      _id: 14,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa61407d1b9558d226bec",
      name: "Оливье с брискетом ",
      description:
        "Салат с маринованной говядиной, малосольными огурцами, муссом из моркови, заправленный домашним майонезом",
      unit: 230,
      price: 280,
      feature: null,
      image: "",
      _id: 15,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa61407d1b9558d226bec",
      name: "Салат с ароматным филе цыпленка и кленовой заправкой",
      description:
        "Микс салатов романо и шпината, с томатами, цукини и сочным филе цыпленка на гриле",
      unit: 210,
      price: 360,
      feature: null,
      image: "",
      _id: 16,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62607d1b9558d226bf1",
      name: "Тыквенный суп крем",
      description: null,
      unit: 250,
      price: 290,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a00000189536a3712eb33d71508418ae380/M_height",
      _id: 17,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62607d1b9558d226bf1",
      name: "Борщ с томленой грудинкой в печи",
      description: null,
      unit: "380/40/20/20/5",
      price: 350,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018948a6699398def242aec442ce15/M_height",
      _id: 18,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62607d1b9558d226bf1",
      name: "Уха на крепком бульоне",
      description: null,
      unit: 290,
      price: 280,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a00000189535f7c41b317cbc4932bfdf57b/M_height",
      _id: 19,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62607d1b9558d226bf1",
      name: "Просто вкусный куриный суп",
      description: null,
      unit: 360,
      price: 260,
      feature: "детское",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a000001895372003d0aa8d88f5074a63c08/M_height",
      _id: 20,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62607d1b9558d226bf1",
      name: "Суп с фрикадельками",
      description: null,
      unit: 260,
      price: 240,
      feature: "детское",
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189536d6c2a8781678030800ea71a/M_height",
      _id: 21,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Пицца маргарита",
      description: null,
      unit: 440,
      price: 520,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a00000189537a6893fc63308d95f91387d0/M_height",
      _id: 22,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Пицца груша дор-блю",
      description: null,
      unit: 450,
      price: 540,
      feature: null,
      image: "",
      _id: 23,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Пицца 4 сыра",
      description: null,
      unit: 455,
      price: 520,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a000001895378b0233df6f1e8d9e215ffa1/M_height",
      _id: 24,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Пицца с пельменями",
      description: null,
      unit: 600,
      price: 510,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a00000189537d67c06b674750de764f0fe0/M_height",
      _id: 25,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Пицца ветчина грибы",
      description: null,
      unit: 530,
      price: 490,
      feature: null,
      image: "",
      _id: 26,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Пицца с куриным бедром и соусом ранч",
      description: null,
      unit: 530,
      price: 520,
      feature: null,
      image: "",
      _id: 27,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Пицца пиперони ",
      description: null,
      unit: 480,
      price: 490,
      feature: "острое",
      image: "",
      _id: 28,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa62e07d1b9558d226bf4",
      name: "Авторский хачапури по-аджарски",
      description: null,
      unit: 380,
      price: 390,
      feature: null,
      image: "",
      _id: 29,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa65807d1b9558d226bfa",
      name: "Добавки в ассортименте",
      description:
        "Сыр моцарелла, Пепперони, Ветчина, Халапенью, Маслины/оливки, Бекон",
      unit: 50,
      price: 70,
      feature: null,
      image: "",
      _id: 30,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa66107d1b9558d226bfd",
      name: "Арабьята",
      description: null,
      unit: 330,
      price: 380,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a0000018953814ff67fbdad82d91c151508/M_height",
      _id: 31,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa66107d1b9558d226bfd",
      name: "Сливочная с лососем и красной икрой",
      description: null,
      unit: 300,
      price: 710,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953af45847459f124205890aec6/M_height",
      _id: 32,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa66107d1b9558d226bfd",
      name: "Болоньезе с шашлыком",
      description: null,
      unit: 310,
      price: 360,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a0000018953aca9a01e2fc59778a5bd8407/M_height",
      _id: 33,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa66107d1b9558d226bfd",
      name: "Карбонара без кое-каких сливок",
      description: null,
      unit: 290,
      price: 360,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a0000018953ae4c85bd5b5aff0b53dd2e00/M_height",
      _id: 34,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Пельмени классические",
      description:
        "Пельмени ручной лепки(свинина/говядина), подается со сметаной",
      unit: 350,
      price: 260,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953b8a4e6cf7a9382641f9b50b0/M_height",
      _id: 35,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Пельмени куриные",
      description: "Пельмени ручной лепки(курица), подается со сметаной",
      unit: 300,
      price: 240,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953b8a4e6cf7a9382641f9b50b0/M_height",
      _id: 36,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Порубленные куриные котлеты с картофельным пюре",
      description: null,
      unit: 320,
      price: 470,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953c465870252358658d44ca61f/M_height",
      _id: 37,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Бифштекс с пшенной кашей из детства",
      description: null,
      unit: 330,
      price: 450,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953c4d43b7e48a798120c7f4853/M_height",
      _id: 38,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Печеный на углях картофель с томленым мясом",
      description: null,
      unit: 350,
      price: 520,
      feature: null,
      image: "",
      _id: 39,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Четверть цыпленка в лаваше",
      description:
        "Цыпленок приготовленный на углях, с овощами и томатным соусом в лаваше.",
      unit: 400,
      price: 530,
      feature: null,
      image: "",
      _id: 40,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Стейк из не горбуши",
      description:
        "Рыба семейства лососевых, подается на подушке из кус-куса с овощами, семенами тыквы и подсолнечника",
      unit: 260,
      price: 790,
      feature: null,
      image: "",
      _id: 41,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa68e07d1b9558d226c01",
      name: "Лопатка говяжья с овощами",
      description:
        "Стейк топ-блед, беби картофель и морковью. Украшен чатни из вишни и микрозеленью",
      unit: "180/150/50",
      price: 840,
      feature: null,
      image: "",
      _id: 42,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6a907d1b9558d226c04",
      name: "Шашлык из свиной шеи",
      description: null,
      unit: "180/40/40",
      price: 380,
      feature: null,
      image: "",
      _id: 43,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6a907d1b9558d226c04",
      name: "Шашлык из куриного бедра",
      description: null,
      unit: "180/40/40",
      price: 350,
      feature: null,
      image: "",
      _id: 44,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6a907d1b9558d226c04",
      name: "Люля-кебаб из говядины и баранины",
      description: null,
      unit: "150/40/40",
      price: 490,
      feature: null,
      image: "",
      _id: 45,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6a907d1b9558d226c04",
      name: "Купаты из свинины",
      description: null,
      unit: "150/40/40",
      price: 320,
      feature: null,
      image: "",
      _id: 46,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6a907d1b9558d226c04",
      name: "Купаты домашние",
      description: null,
      unit: "150/40/40",
      price: 340,
      feature: null,
      image: "",
      _id: 47,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6d407d1b9558d226c08",
      name: "Картофель фри",
      description: null,
      unit: 150,
      price: 210,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d69b92396bfb584c5736a7a2/M_height",
      _id: 48,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6d407d1b9558d226c08",
      name: "Картофельное пюре",
      description: null,
      unit: 150,
      price: 180,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d2183a2b780558d530a4c836/M_height",
      _id: 49,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6d407d1b9558d226c08",
      name: "Картофель беби",
      description: null,
      unit: 150,
      price: 150,
      feature: null,
      image: "",
      _id: 50,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6d407d1b9558d226c08",
      name: "Овощи на пару",
      description: null,
      unit: 150,
      price: 190,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d61427670ad5293d33cf235b/M_height",
      _id: 51,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6d407d1b9558d226c08",
      name: "Овощи на гриле",
      description: null,
      unit: 150,
      price: 210,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018953b24b40c912f63cd57a2736ec/M_height",
      _id: 52,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa6eb07d1b9558d226c0c",
      name: "Соусы в ассортименте",
      description:
        "томатный с травами, сырный, барбекю, кетчуп, сметана, майонез, чили остро-сладкий, ягодный, сгущенка",
      unit: 40,
      price: 50,
      feature: null,
      image: "",
      _id: 53,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Манговый медовик",
      description:
        "Пропитанные медовые коржи в сочетании со сметанным кремом и прослойкой из мангового пюре. Украшен ягодами голубики.",
      unit: 150,
      price: 230,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018953d97aa4abfd34ccb3616963a0/M_height",
      _id: 54,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Торт Красный бархат",
      description: "Красный бисквит с начинкой крем чиз и клубникой",
      unit: 150,
      price: 230,
      feature: null,
      image: "",
      _id: 55,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Наполеон малиновый",
      description:
        "Слоеное тесто собственного производства в сочетании с заварным кремом и прослойкой из малинового соуса.",
      unit: "150",
      price: 230,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018953d811db09cfb11ef9c53c6d06/M_height",
      _id: 56,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Чизкейк с ягодным соусом",
      description:
        "классический чизкейк на корже из песочного теста. Подается с ягодным соусом.",
      unit: "150",
      price: 280,
      feature: null,
      image: "",
      _id: 57,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Шоколадный чиз",
      description:
        "Классический чизкейк с добавлением шоколада на корже из песочного теста. Украшен шоколадной крошкой.",
      unit: "150",
      price: 285,
      feature: null,
      image: "",
      _id: 58,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Торт Эстерхази",
      description:
        "Фундучный бисквит выпекается без муки, с молочно-карамельной начинкой украшен грецким орехом и лепестками миндаля",
      unit: "150",
      price: 270,
      feature: null,
      image: "",
      _id: 59,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Меренговый рулет",
      description:
        "Основа - нежная хрустящая меренга, с кремом чиз и манговой прослойкой. Украшен мятой и свежей клубникой.",
      unit: "150",
      price: 240,
      feature: null,
      image: "",
      _id: 60,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Торт Сникерс",
      description:
        "Шоколадный бисквит с сливочно сырным кремом с соленой карамелью и арахисом.",
      unit: "150",
      price: 220,
      feature: null,
      image: "",
      _id: 61,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Торт Маковый с Лимоном",
      description:
        "Маковый нежный бисквит с ванильным крем чизом и лимонным куртом.",
      unit: "150",
      price: 260,
      feature: null,
      image: "",
      _id: 62,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Торт Красный бархат",
      description: "Красный бисквит с начинкой крем чиз и клубникой",
      unit: "150",
      price: 230,
      feature: null,
      image: "",
      _id: 63,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Торт Шоколадно-банановый",
      description:
        "Маковый нежный бисквит с ванильным крем чизом и лимонным куртом",
      unit: "150",
      price: 220,
      feature: null,
      image: "",
      _id: 64,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Капкейк малина",
      description:
        "Шоколадный бисквит с начинкой из малинового пюре, украшен шапкой из крем чиза",
      unit: "150",
      price: 110,
      feature: null,
      image: "",
      _id: 65,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Капкейк банан",
      description:
        "Шоколадный бисквит с начинкой из свежего банана, украшен шапкой из крем чиза",
      unit: "150",
      price: 100,
      feature: null,
      image: "",
      _id: 66,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Капкейк соленая карамель",
      description:
        "Шоколадный бисквит с начинкой из малинового пюре, украшен шапкой из крем чиз",
      unit: "150",
      price: 100,
      feature: null,
      image: "",
      _id: 67,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Кейк-поп",
      description: null,
      unit: 50,
      price: 80,
      feature: null,
      image: "",
      _id: 68,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Тарт лимонный",
      description:
        " Основа из песочного теста, начинка из лимонного курда и украшенные белковым кремом, миндальными лепестками и долькой карамелизированного лимона",
      unit: 120,
      price: 150,
      feature: null,
      image: "",
      _id: 69,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Тарт грушевый",
      description:
        "Основа из песочного теста, начинка из груши и корицы, запеченная в сметане ",
      unit: 120,
      price: 150,
      feature: null,
      image: "",
      _id: 70,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Тарт банан и соленая карамель",
      description:
        "Основа из песочного теста, начинка из банана, карамели, украшен взбитыми сливками",
      unit: 120,
      price: 150,
      feature: null,
      image: "",
      _id: 71,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa70007d1b9558d226c0f",
      name: "Торт на заказ ",
      description: "В ассортименте",
      unit: 1000,
      price: 0,
      feature: null,
      image: "",
      _id: 72,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Просто вкусные сырники с манговым соусом",
      description: null,
      unit: 190,
      price: 220,
      feature: null,
      image: "",
      _id: 73,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Черничная рисовая каша",
      description: null,
      unit: 250,
      price: 180,
      feature: null,
      image: "",
      _id: 74,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Блины на манер креп Сюзет с фруктами",
      description: null,
      unit: 250,
      price: 220,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a000001894521b8d68cf5d6b371d3cefde2/M_height",
      _id: 75,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Глазунья Цезарь",
      description: null,
      unit: 250,
      price: 180,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a000001894512041ea29ddccfc29a2eab8c/M_height",
      _id: 76,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Омлет с овощами и луковым вареньем",
      description: null,
      unit: 350,
      price: 210,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a00000189451c5a7fa690ba3613bf631275/M_height",
      _id: 77,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Бенедикт с лососем, томатами и авокадо",
      description: null,
      unit: 330,
      price: 440,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a00000189452d9670987ffd55a2f239592a/M_height",
      _id: 78,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Драник картофельный \nсо сметаной",
      description: null,
      unit: 170,
      price: 140,
      feature: null,
      image: "",
      _id: 79,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Драник картофельный  с слабосоленой красной рыбой",
      description: null,
      unit: 200,
      price: 320,
      feature: null,
      image: "",
      _id: 80,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Драник картофельный с томленной грудинкой",
      description: null,
      unit: 200,
      price: 250,
      feature: null,
      image: "",
      _id: 81,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa71507d1b9558d226c12",
      name: "Шакшука классическая",
      description: null,
      unit: "210/50",
      price: 220,
      feature: null,
      image: "",
      _id: 82,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Салат Имбирный цыпленок с киноа и томатами",
      description: null,
      unit: 140,
      price: 170,
      feature: null,
      image: "",
      _id: 83,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Зеленый салат с киноа",
      description: null,
      unit: 140,
      price: 130,
      feature: null,
      image: "",
      _id: 84,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Куриный суп с лапшой",
      description: null,
      unit: 300,
      price: 120,
      feature: null,
      image: "",
      _id: 85,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Суп гуляш",
      description: null,
      unit: 300,
      price: 180,
      feature: null,
      image: "",
      _id: 86,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Бефстроганов с картофельным пюре",
      description: null,
      unit: 300,
      price: 240,
      feature: null,
      image: "",
      _id: 87,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Котлеты пожарские с картофельным пюре",
      description: null,
      unit: 290,
      price: 190,
      feature: null,
      image: "",
      _id: 88,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Напиток дня",
      description:
        "Чай: черный/зеленый, кофе: американо/капучино, морс в ассортименте",
      unit: "1",
      price: 75,
      feature: null,
      image: "",
      _id: 89,
    },
    {
      menu: "Основное меню",
      categoryId: "667aa72e07d1b9558d226c15",
      name: "Десерт дня",
      description: null,
      unit: "1",
      price: 100,
      feature: null,
      image: "",
      _id: 90,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Эспрессо",
      description: "Кофе",
      unit: 40,
      price: 80,
      feature: null,
      image: "",
      _id: 91,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Американо",
      description: "Кофе, вода",
      unit: 250,
      price: 120,
      feature: null,
      image: "",
      _id: 92,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Капучино ",
      description: "Кофе, молоко",
      unit: 250,
      price: 140,
      feature: null,
      image: "",
      _id: 93,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Латте",
      description: "Кофе, молоко",
      unit: 250,
      price: 150,
      feature: null,
      image: "",
      _id: 94,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Флет уайт",
      description: "Кофе, молоко",
      unit: 250,
      price: 160,
      feature: null,
      image: "",
      _id: 95,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Раф",
      description: "Кофе, сливки, сироп ",
      unit: 250,
      price: 220,
      feature: null,
      image: "",
      _id: 96,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Капучино на банановом/кокосовом",
      description: null,
      unit: 250,
      price: 180,
      feature: null,
      image: "",
      _id: 97,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Капучино с лавандой",
      description: null,
      unit: 250,
      price: 160,
      feature: null,
      image: "",
      _id: 98,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Капучино с малиной",
      description: null,
      unit: 250,
      price: 180,
      feature: null,
      image: "",
      _id: 99,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Банановый фраппе",
      description: null,
      unit: 300,
      price: 170,
      feature: null,
      image: "",
      _id: 100,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Матча латте",
      description: null,
      unit: 250,
      price: 180,
      feature: null,
      image: "",
      _id: 101,
    },
    {
      menu: "Бар",
      categoryId: "_17",
      name: "Матча латте (на альтернативном молоке)",
      description: null,
      unit: 250,
      price: 220,
      feature: null,
      image: "",
      _id: 102,
    },
    {
      menu: "Бар",
      categoryId: "_16",
      name: "Облачное какао",
      description:
        "Классический какао с маршмеллоу, взбитыми сливками и сиропом",
      unit: 200,
      price: 250,
      feature: null,
      image: "",
      _id: 103,
    },
    {
      menu: "Бар",
      categoryId: "_16",
      name: "Классическое какао",
      description:
        "Классический какао с маршмеллоу, взбитыми сливками и сиропом",
      unit: 200,
      price: 190,
      feature: null,
      image: "",
      _id: 104,
    },
    {
      menu: "Бар",
      categoryId: "_16",
      name: "Белый шоколад Малина-Питахайя",
      description:
        "Белый шоколад со вкусом малины и питахайи с сублимированной малиной",
      unit: 200,
      price: 210,
      feature: null,
      image: "",
      _id: 105,
    },
    {
      menu: "Бар",
      categoryId: "_16",
      name: "Шоколадная бомба",
      description: null,
      unit: "",
      price: 290,
      feature: null,
      image: "",
      _id: 106,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Черный",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 107,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Черный Черная смородина",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 108,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Черный Барбарислвый",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 109,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "ПуЭр Юннань",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 110,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Зеленый сенча",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 111,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Зеленый Дыня-Карамель",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 112,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Зеленый с жасмином",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 113,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Улун молочный",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 114,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Травяной Лимон с Имбирем",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 115,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Каркаде",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 116,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Дерзкий фрукт",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 117,
    },
    {
      menu: "Бар",
      categoryId: "_15",
      name: "Чай Мятный Каркаде",
      description: null,
      unit: "600 мл.",
      price: 150,
      feature: null,
      image: "",
      _id: 118,
    },
    {
      menu: "Бар",
      categoryId: "_14",
      name: "Мята",
      description: null,
      unit: "5",
      price: 30,
      feature: null,
      image: "",
      _id: 119,
    },
    {
      menu: "Бар",
      categoryId: "_14",
      name: "Мед",
      description: null,
      unit: 30,
      price: 50,
      feature: null,
      image: "",
      _id: 120,
    },
    {
      menu: "Бар",
      categoryId: "_14",
      name: "Лимон",
      description: null,
      unit: "50",
      price: 30,
      feature: null,
      image: "",
      _id: 121,
    },
    {
      menu: "Бар",
      categoryId: "_14",
      name: "Чабрец",
      description: null,
      unit: "5",
      price: 30,
      feature: null,
      image: "",
      _id: 122,
    },
    {
      menu: "Бар",
      categoryId: "_13",
      name: "Персик-розмарин",
      description: null,
      unit: "600 мл.",
      price: 250,
      feature: null,
      image: "",
      _id: 123,
    },
    {
      menu: "Бар",
      categoryId: "_13",
      name: "Лемонграсс-киви",
      description: null,
      unit: "600 мл.",
      price: 250,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a00000189981c21180e5462c9793dda968f/M_height",
      _id: 124,
    },
    {
      menu: "Бар",
      categoryId: "_13",
      name: "Черная смородина-каркаде",
      description: null,
      unit: "600 мл.",
      price: 250,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a000001899818ff997bc6ac5a49c160cc56/M_height",
      _id: 125,
    },
    {
      menu: "Бар",
      categoryId: "_13",
      name: "Облепиха глинтвейн",
      description: null,
      unit: "600 мл.",
      price: 250,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a00000189981b6202385e9e15fc07c6d874/M_height",
      _id: 126,
    },
    {
      menu: "Бар",
      categoryId: "_13",
      name: "Гранатовый",
      description: null,
      unit: "600 мл.",
      price: 250,
      feature: null,
      image: "",
      _id: 127,
    },
    {
      menu: "Бар",
      categoryId: "_13",
      name: "Груша-жасмин",
      description: null,
      unit: "600 мл.",
      price: 250,
      feature: null,
      image: "",
      _id: 128,
    },
    {
      menu: "Бар",
      categoryId: "_13",
      name: "Цитрусовый",
      description: null,
      unit: "600 мл.",
      price: 250,
      feature: null,
      image: "",
      _id: 129,
    },
    {
      menu: "Бар",
      categoryId: "_12",
      name: "Ягодный лемонграсс",
      description: null,
      unit: "300/1000мл",
      price: 90,
      feature: null,
      image: "",
      _id: 130,
    },
    {
      menu: "Бар",
      categoryId: "_12",
      name: "Клюква-Имбирь",
      description: null,
      unit: "300/1000мл",
      price: 90,
      feature: null,
      image: "",
      _id: 131,
    },
    {
      menu: "Бар",
      categoryId: "_12",
      name: "Облепиха-вишня",
      description: null,
      unit: "300/1000мл",
      price: 90,
      feature: null,
      image: "",
      _id: 132,
    },
    {
      menu: "Бар",
      categoryId: "_12",
      name: "Апельсин-мандарин",
      description: null,
      unit: "300/1000мл",
      price: 90,
      feature: null,
      image: "",
      _id: 133,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Классический Лимонад",
      description: "Сок Лимона, сахарный сироп, лимон, мята, содовая",
      unit: "1000 мл.",
      price: 250,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018997c773ba69e5dbb954266598da/M_height",
      _id: 134,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Тархун",
      description: "Сироп Тархун, сок лимона, лимон",
      unit: "1000 мл.",
      price: 290,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9685839/2a0000018997c99b5bd00075391791cc2745/M_height",
      _id: 135,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Маракуйя-матча",
      description:
        "Пюре Маракуйя, сироп маракуйя, сахарный сироп, сок лимона, чай матча",
      unit: "1000 мл.",
      price: 290,
      feature: null,
      image: "",
      _id: 136,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Груша-Базилик",
      description: "Сироп груша, свежий базилик, сок лимона",
      unit: "1000 мл.",
      price: 290,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9240521/2a0000018997b09d8e14bcc2fd3dbdf725bb/M_height",
      _id: 137,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Облепиха-Тархун",
      description: "Сироп облепиха, сироп тархун, сок лимона, апельсин",
      unit: "1000 мл.",
      price: 290,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9495815/2a0000018997b5ab275ac77d2cce7fea5937/M_height",
      _id: 138,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Грейпфрут-Бабл гам",
      description:
        "Грейпфрутовый сок, сироп бабл гам, сок лимона, лайм, сахарный сироп",
      unit: 1000,
      price: 290,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a00000189979a97d6ff5734cd945805566b/M_height",
      _id: 139,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Лаванда-Малина",
      description: "Сироп лаванда, сироп малина, сок лимона, апельсин",
      unit: 1000,
      price: 290,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5399152/2a0000018997a0fbd928177c090811bea13a/M_height",
      _id: 140,
    },
    {
      menu: "Бар",
      categoryId: "_11",
      name: "Ананас-миндаль",
      description:
        "Ананасовый сок, сахарный сироп, сироп миндаль, сок лимона,мята, лайм ",
      unit: 1000,
      price: 290,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/9854027/2a0000018997a41451f801db1c8569ca1b9d/M_height",
      _id: 141,
    },
    {
      menu: "Бар",
      categoryId: "_10",
      name: "Вода газ /негаз",
      description: null,
      unit: 330,
      price: 120,
      feature: null,
      image: "",
      _id: 142,
    },
    {
      menu: "Бар",
      categoryId: "_10",
      name: "Сок в ассортименте (вишня, яблоко, ананас, грейпфрут, апельсин, персик)",
      description: null,
      unit: 200,
      price: 180,
      feature: null,
      image: "",
      _id: 143,
    },
    {
      menu: "Бар",
      categoryId: "_10",
      name: "Газированные напитки (в ассортименте)",
      description: null,
      unit: 330,
      price: 150,
      feature: null,
      image: "",
      _id: 144,
    },
    {
      menu: "Бар",
      categoryId: "_9",
      name: "Апероль БА",
      description: null,
      unit: 200,
      price: 200,
      feature: null,
      image: "",
      _id: 145,
    },
    {
      menu: "Бар",
      categoryId: "_9",
      name: "Мохито БА ",
      description: null,
      unit: 200,
      price: 200,
      feature: null,
      image: "",
      _id: 146,
    },
    {
      menu: "Бар",
      categoryId: "_9",
      name: "Мандариновый Тархун",
      description: null,
      unit: 200,
      price: 190,
      feature: null,
      image: "",
      _id: 147,
    },
    {
      menu: "Бар",
      categoryId: "_9",
      name: "Курасао",
      description: null,
      unit: 200,
      price: 200,
      feature: null,
      image: "",
      _id: 148,
    },
    {
      menu: "Бар",
      categoryId: "_9",
      name: "Глинтвейн БА",
      description: null,
      unit: 350,
      price: 230,
      feature: null,
      image: "",
      _id: 149,
    },
    {
      menu: "Бар",
      categoryId: "_8",
      name: "Киви",
      description: null,
      unit: 250,
      price: 230,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a0000018954466f579c74945b8d497da518/M_height",
      _id: 150,
    },
    {
      menu: "Бар",
      categoryId: "_8",
      name: "Банан-шоколад",
      description: null,
      unit: 250,
      price: 230,
      feature: null,
      image: "",
      _id: 151,
    },
    {
      menu: "Бар",
      categoryId: "_8",
      name: "Классический ",
      description: null,
      unit: 250,
      price: 210,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a0000018954466f579c74945b8d497da518/M_height",
      _id: 152,
    },
    {
      menu: "Бар",
      categoryId: "_8",
      name: "Карамельный",
      description: null,
      unit: 250,
      price: 230,
      feature: null,
      image:
        "https://avatars.mds.yandex.net/get-sprav-products/5236693/2a0000018954466f579c74945b8d497da518/M_height",
      _id: 153,
    },
    {
      menu: "Бар",
      categoryId: "_8",
      name: "Клубничный",
      description: null,
      unit: 250,
      price: 230,
      feature: null,
      image: "",
      _id: 154,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Мандарин Рояль",
      description: null,
      unit: 200,
      price: 310,
      feature: null,
      image: "",
      _id: 155,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Мимоза",
      description: null,
      unit: 200,
      price: 280,
      feature: null,
      image: "",
      _id: 156,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Кир рояль",
      description: null,
      unit: 200,
      price: 290,
      feature: null,
      image: "",
      _id: 157,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Титаник",
      description: null,
      unit: 200,
      price: 250,
      feature: null,
      image: "",
      _id: 158,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Апероль Спритц",
      description: null,
      unit: 200,
      price: 310,
      feature: null,
      image: "",
      _id: 159,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Беллини",
      description: null,
      unit: 200,
      price: 310,
      feature: null,
      image: "",
      _id: 160,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Фиеро Тоник",
      description: null,
      unit: 200,
      price: 310,
      feature: null,
      image: "",
      _id: 161,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Клубничный Сауер",
      description: null,
      unit: 200,
      price: 290,
      feature: null,
      image: "",
      _id: 162,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Ягодно-ванильный сауэр",
      description: null,
      unit: 200,
      price: 270,
      feature: null,
      image: "",
      _id: 163,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Черносмородиновый Сауер",
      description: null,
      unit: 200,
      price: 310,
      feature: null,
      image: "",
      _id: 164,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Глинтвейн на белом вине",
      description: null,
      unit: 200,
      price: 310,
      feature: null,
      image: "",
      _id: 165,
    },
    {
      menu: "Бар",
      categoryId: "_7",
      name: "Глинтвейн на красном вине",
      description: null,
      unit: 200,
      price: 300,
      feature: null,
      image: "",
      _id: 166,
    },
    {
      menu: "Бар",
      categoryId: "_6",
      name: "Новый свет",
      description: "Россия, Розовое, п/сл",
      unit: 750,
      price: 2100,
      feature: null,
      image: "",
      _id: 167,
    },
    {
      menu: "Бар",
      categoryId: "_6",
      name: "Аристов ",
      description: "Кубань, белое, брют",
      unit: 750,
      price: 1500,
      feature: null,
      image: "",
      _id: 168,
    },
    {
      menu: "Бар",
      categoryId: "_6",
      name: "Глера Спуманте Фонте ",
      description: "Италия, белое, extra dry",
      unit: 750,
      price: 2500,
      feature: null,
      image: "",
      _id: 169,
    },
    {
      menu: "Бар",
      categoryId: "_6",
      name: "Просекко Болла",
      description: "Италия, белое, сухое",
      unit: 200,
      price: 400,
      feature: null,
      image: "",
      _id: 170,
    },
    {
      menu: "Бар",
      categoryId: "_5",
      name: "Рислинг Бекштайнер",
      description: "Германия, белое, сухое",
      unit: 750,
      price: 2250,
      feature: null,
      image: "",
      _id: 171,
    },
    {
      menu: "Бар",
      categoryId: "_5",
      name: "Арко бэйМальборо Совиньон Блан",
      description: "Новая зеландия, белое, сухое",
      unit: 750,
      price: 2950,
      feature: null,
      image: "",
      _id: 172,
    },
    {
      menu: "Бар",
      categoryId: "_5",
      name: "Винье Верде Альту Лима",
      description: "Португалия, белое, сухое",
      unit: 750,
      price: 1600,
      feature: null,
      image: "",
      _id: 173,
    },
    {
      menu: "Бар",
      categoryId: "_5",
      name: "Геометрия Кокур",
      description: "Крым, белое, п/сух",
      unit: 750,
      price: 1800,
      feature: null,
      image: "",
      _id: 174,
    },
    {
      menu: "Бар",
      categoryId: "_5",
      name: "Ривер Рут ГевюрцРаминер",
      description: "Германия, Полусладкое",
      unit: 750,
      price: 1850,
      feature: null,
      image: "",
      _id: 175,
    },
    {
      menu: "Бар",
      categoryId: "_5",
      name: "Мскат Массандра",
      description: "Крым, п/сл",
      unit: 750,
      price: 1600,
      feature: null,
      image: "",
      _id: 176,
    },
    {
      menu: "Бар",
      categoryId: "_5",
      name: "Палавани Алазанская долина (Ркацители)",
      description: "Грузия, п/сл",
      unit: 750,
      price: 1800,
      feature: null,
      image: "",
      _id: 177,
    },
    {
      menu: "Бар",
      categoryId: "_4",
      name: "Вайнкеллерай Ленц Мозер Цвайгельт Розе",
      description: "Австрия, сухое",
      unit: 750,
      price: 1950,
      feature: null,
      image: "",
      _id: 178,
    },
    {
      menu: "Бар",
      categoryId: "_4",
      name: "Павао Розе",
      description: "Португалия, п/сух",
      unit: 750,
      price: 1600,
      feature: null,
      image: "",
      _id: 179,
    },
    {
      menu: "Бар",
      categoryId: "_3",
      name: "Сады Армении Гранат",
      description: "Армения, Гранатовое, п/сл",
      unit: 750,
      price: 1350,
      feature: null,
      image: "",
      _id: 180,
    },
    {
      menu: "Бар",
      categoryId: "_3",
      name: "ШанХазарян Малина",
      description: "Армения, Малиновое, п/сл",
      unit: 750,
      price: 1550,
      feature: null,
      image: "",
      _id: 181,
    },
    {
      menu: "Бар",
      categoryId: "_2",
      name: "Каберне ",
      description: "Крым, красное, сухое",
      unit: 750,
      price: 1200,
      feature: null,
      image: "",
      _id: 182,
    },
    {
      menu: "Бар",
      categoryId: "_2",
      name: "Трапиче Вильярдс Мальбек",
      description: "Аргентина, красное, сухое",
      unit: 750,
      price: 2200,
      feature: null,
      image: "",
      _id: 183,
    },
    {
      menu: "Бар",
      categoryId: "_2",
      name: "Пино Нуар Пэид'ок Мэзон Кастель",
      description: "Франция, красное, сухое",
      unit: 750,
      price: 2850,
      feature: null,
      image: "",
      _id: 184,
    },
    {
      menu: "Бар",
      categoryId: "_2",
      name: "Кукабара Каберне Совиньон",
      description: "Австралия, красное, п/сух",
      unit: 750,
      price: 1500,
      feature: null,
      image: "",
      _id: 185,
    },
    {
      menu: "Бар",
      categoryId: "_2",
      name: "Шато Руж",
      description: "Крым, красное, п/сух",
      unit: 750,
      price: 1200,
      feature: null,
      image: "",
      _id: 186,
    },
    {
      menu: "Бар",
      categoryId: "_2",
      name: "Абшерон Шараб",
      description: "Азербайджан, красное, п/сл",
      unit: 750,
      price: 1600,
      feature: null,
      image: "",
      _id: 187,
    },
    {
      menu: "Бар",
      categoryId: "_2",
      name: "Палавани Алазанская долина (Саперави)",
      description: "Грузия, красное , п/сл",
      unit: 750,
      price: 1800,
      feature: null,
      image: "",
      _id: 188,
    },
    {
      menu: "Бар",
      categoryId: "_1",
      name: "Крюгер Пилснер",
      description: "Светлое, фильтрованное",
      unit: 500,
      price: 250,
      feature: null,
      image: "",
      _id: 189,
    },
    {
      menu: "Бар",
      categoryId: "_1",
      name: "Крюгер Дункель",
      description: "Темное, фильтрованное",
      unit: 500,
      price: 250,
      feature: null,
      image: "",
      _id: 190,
    },
    {
      menu: "Бар",
      categoryId: "_1",
      name: "Харвестр",
      description: "Светлое, нефильтрованное",
      unit: 500,
      price: 250,
      feature: null,
      image: "",
      _id: 191,
    },
    {
      menu: "Бар",
      categoryId: "_1",
      name: "Аркобой Мозер Лизель",
      description: "Светлое, фильтрованное",
      unit: 500,
      price: 490,
      feature: null,
      image: "",
      _id: 192,
    },
    {
      menu: "Бар",
      categoryId: "_1",
      name: "Либейнвайс Хефе-Вайсиб",
      description: "Светлое, нефильтрованное",
      unit: 500,
      price: 480,
      feature: null,
      image: "",
      _id: 193,
    },
    {
      menu: "Бар",
      categoryId: "_1",
      name: "Черновар",
      description: "Темное, фильтрованное",
      unit: 500,
      price: 480,
      feature: null,
      image: "",
      _id: 194,
    },
    {
      menu: "Бар",
      categoryId: "_1",
      name: "Бакалар (б/а)",
      description: "Светлое, фильтрованное, безалкогольное",
      unit: 500,
      price: 295,
      feature: null,
      image: "",
      _id: 195,
    },
  ];

  const categories: Category[] = [
    {
      title: {
        ru: "Кофе",
        en: "Coffee",
      },
      slug: "coffee",
      _id: "_17",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Какао & Горячий шоколад",
        en: "Cocoa and Hot Chocolate",
      },
      slug: "hot_chocolate",
      _id: "_16",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Чай",
        en: "Tea",
      },
      slug: "tea",
      _id: "_15",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Добавки к чаю",
        en: "Tea additives",
      },
      slug: "tea_additives",
      _id: "_14",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Авторский Чай",
        en: "Author's Tea",
      },
      slug: "authors_tea",
      _id: "_13",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Морсы",
        en: "Fruit drinks",
      },
      slug: "friut_drinks",
      _id: "_12",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Лимонады",
        en: "Lemonades",
      },
      slug: "lemonades",
      _id: "_11",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Напитки",
        en: "Beverages",
      },
      slug: "beverages",
      _id: "_10",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Коктели БА",
        en: "Cocktails (W/A)",
      },
      slug: "cocktails",
      _id: "_9",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Милшейки",
        en: "Milsheyki",
      },
      slug: "milkshakes",
      _id: "_8",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Алкогольные коктейли",
        en: "Alcoholic cocktails",
      },
      slug: "cocktail",
      _id: "_7",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Вино",
        en: "Wine",
      },
      slug: "wine",
      _id: "_6",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Белые Вина",
        en: "White Wines",
      },
      slug: "white_wine",
      _id: "_5",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Розовые Вина",
        en: "Rose Wines",
      },
      slug: "pink_wine",
      _id: "_4",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Не виноградные вина",
        en: "Not grape wines",
      },
      slug: "no_red_wine",
      _id: "_3",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Красные Вина",
        en: "Red Wines",
      },
      slug: "red_wine",
      _id: "_2",
      description: { ru: "" },
    },
    {
      title: {
        ru: "Пиво",
        en: "Beer",
      },
      slug: "beer",
      _id: "_1",
      description: { ru: "" },
    },
  ];

  return {
    menu,
    categories,
  };
}
