export default function () {
  const menu = [
    {
      name: "сырники с манговой сгущенкой",
      portion_size: "190",
      price: 200,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 1,
    },
    {
      name: "каша овсяная с ягодами",
      portion_size: "250",
      price: 240,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 2,
    },
    {
      name: "черничная рисовая каша",
      portion_size: "250",
      price: 180,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 3,
    },
    {
      name: "оладьи с соусом и халвой",
      portion_size: "240",
      price: 170,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 4,
    },
    {
      name: "блины с фруктами",
      portion_size: "250",
      price: 220,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 5,
    },
    {
      name: "глазунья цезарь",
      portion_size: "250",
      price: 180,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 6,
    },
    {
      name: "омлет с овощами и луковым вареньем",
      portion_size: "350",
      price: 210,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 7,
    },
    {
      name: "бенедикт с лососем, сладкими томатами и авокадо",
      portion_size: "330",
      price: 440,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 8,
    },
    {
      name: "бенедикт с мясом, малосольными огурцами",
      portion_size: "330",
      price: 420,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 9,
    },
    {
      name: "пончики с фруктовым тартаром",
      portion_size: "220",
      price: 280,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "завтраки до 13:00",
      id: 10,
    },
    {
      name: "стрипсы из индейки с морковным барбекю",
      portion_size: "160/30/30",
      price: 450,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 11,
    },
    {
      name: "сендвич blt с уникальным соусом",
      portion_size: "300",
      price: 410,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 12,
    },
    {
      name: "сендвич бан ми",
      portion_size: "250",
      price: 390,
      unit: "гр",
      image: "",
      description:
        "в начинку используется пашет из мяса птицы и томленой грудинкой. дополняем свежими овощами и соусом с азиатскими нотками.",
      is_kids_menu: false,
      category: "закуски",
      id: 13,
    },
    {
      name: "тартин с лососем и мягким сыром",
      portion_size: "170",
      price: 420,
      unit: "гр",
      image: "",
      description:
        "открытый сендвич с лососем слабого посола, мягким сыром и сладким помидором.",
      is_kids_menu: false,
      category: "закуски",
      id: 14,
    },
    {
      name: "тартин с говядиной и огурцами малой соли",
      portion_size: "50",
      price: 380,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 15,
    },
    {
      name: "баклажаны с томатами в кисло-сладком соусе из кленового сиропа",
      portion_size: "150",
      price: 280,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 16,
    },
    {
      name: "эклер с мерлузой и щучьей икрой",
      portion_size: "100",
      price: 310,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 17,
    },
    {
      name: "тартар из говядины с пирожочками с луковым джемом",
      portion_size: "250",
      price: 450,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 18,
    },
    {
      name: "рийет из рыбы с хлебом",
      portion_size: "180",
      price: 390,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 19,
    },
    {
      name: "жареный картофель со сметаной и икрой",
      portion_size: "230",
      price: 280,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "закуски",
      id: 20,
    },
    {
      name: "оливье с томленым мясом и юньским горошком",
      portion_size: "230",
      price: 260,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "салаты",
      id: 21,
    },
    {
      name: "мимоза с соусом тум",
      portion_size: "270",
      price: 280,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "салаты",
      id: 22,
    },
    {
      name: "с говяжьей грудинкой из печи",
      portion_size: "220",
      price: 380,
      unit: "гр",
      image: "",
      description:
        "говяжья грудинка, листья салата, печеный перец цукини, огурцы, дополнено чатни из вишни",
      is_kids_menu: false,
      category: "салаты",
      id: 23,
    },
    {
      name: "борщ с томленой грудинкой",
      portion_size: "380/40/20/20/5",
      price: 350,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "супы",
      id: 24,
    },
    {
      name: "просто вкусный куриный суп",
      portion_size: "360",
      price: 240,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "супы",
      id: 25,
    },
    {
      name: "уха на крепком бульоне",
      portion_size: "290",
      price: 260,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "супы",
      id: 26,
    },
    {
      name: "суп с фрикадельками",
      portion_size: "260",
      price: 220,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: true,
      category: "супы",
      id: 27,
    },
    {
      name: "тыквенный суп-крем",
      portion_size: "250",
      price: 280,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "супы",
      id: 28,
    },
    {
      name: "пельмени классические",
      portion_size: "350",
      price: 240,
      unit: "гр",
      image: "",
      description: "с зеленью, черным перцем и бульоном",
      is_kids_menu: true,
      category: "основные блюда",
      id: 29,
    },
    {
      name: "пельмени куриные",
      portion_size: "300",
      price: 220,
      unit: "гр",
      image: "",
      description: "с зеленью, черным перцем и бульоном",
      is_kids_menu: true,
      category: "основные блюда",
      id: 30,
    },
    {
      name: "рубленые куриные котлеты с картофельным пюре",
      portion_size: "320",
      price: 450,
      unit: "гр",
      image: "",
      description:
        "рубленые котлеты с пюре на сливках и сливочном масле, подается с помидорками",
      is_kids_menu: true,
      category: "основные блюда",
      id: 31,
    },
    {
      name: "бифштекс с пшенной кашей из детства",
      portion_size: "330",
      price: 400,
      unit: "гр",
      image: "",
      description:
        "каша приготовлена методом ризотто. бифштекс на гриле, сопровождается тартаром из огурца и соусом демиглас",
      is_kids_menu: true,
      category: "основные блюда",
      id: 32,
    },
    {
      name: "томленое мясо с печеным в костре картофелем",
      portion_size: "350",
      price: 650,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "основные блюда",
      id: 33,
    },
    {
      name: "кое-чья шаурма",
      portion_size: "400",
      price: 550,
      unit: "гр",
      image: "",
      description:
        "блюдо подается с соусом томатным, соусом майо и букетом из зелени",
      is_kids_menu: false,
      category: "основные блюда",
      id: 34,
    },
    {
      name: "наши пироги с кое-каким мясом из печи",
      portion_size: "550/550",
      price: 450,
      unit: "гр",
      image: "",
      description: "говядина или курица на выбор",
      is_kids_menu: false,
      category: "основные блюда",
      id: 35,
    },
    {
      name: "стейк из не горбуши",
      portion_size: "260",
      price: 790,
      unit: "гр",
      image: "",
      description:
        "лосось/семга запекается в печи, подается с кус-кусом, с семенами подсолнечника, тыквы",
      is_kids_menu: false,
      category: "основные блюда",
      id: 36,
    },
    {
      name: "лопатка говяжья с овощами и вишней",
      portion_size: "180гр/150гр/50гр",
      price: 820,
      unit: "гр",
      image: "",
      description: "",
      is_kids_menu: false,
      category: "основные блюда",
      id: 37,
    },
    {
      name: "маргарита",
      portion_size: "440",
      unit: "гр",
      price: 490,
      image: "",
      description:
        "томатный соус собственного производства, сыр моцарелла, свежий базилик",
      is_kids_menu: false,
      category: "пицца",
      id: 38,
    },
    {
      name: "4 сыра",
      portion_size: "455",
      unit: "гр",
      price: 520,
      image: "",
      description: "пицца с четырьмя видами сыра",
      is_kids_menu: false,
      category: "пицца",
      id: 39,
    },
    {
      name: "с пельменями",
      portion_size: "600",
      unit: "гр",
      price: 510,
      image: "",
      description: "сметанный соус, пельмени, малосольные огурцы",
      is_kids_menu: true,
      category: "пицца",
      id: 40,
    },
    {
      name: "пеперони",
      portion_size: "480",
      unit: "гр",
      price: 490,
      image: "",
      description: "томатный соус собственного производства, ломтики пеперони",
      is_kids_menu: false,
      category: "пицца",
      id: 41,
    },
    {
      name: "арабьята",
      portion_size: "330",
      unit: "гр",
      price: 380,
      image: "",
      description:
        "соус из томатов, печеных перцев с небольшой ноткой чили перца. используется паста пенне.",
      is_kids_menu: false,
      category: "паста",
      id: 42,
    },
    {
      name: "с лососем, сливками и икрой",
      portion_size: "300",
      unit: "гр",
      price: 710,
      image: "",
      description:
        "соус на сливках, белом вине с тимьяном и филе красной рыбы. дополняется икрой. используется паста пенне.",
      is_kids_menu: false,
      category: "паста",
      id: 43,
    },
    {
      name: "болоньезе с шашлыком",
      portion_size: "310",
      unit: "гр",
      price: 360,
      image: "",
      description:
        "соус из фарша, томатов, овощей, вина. сопровождается шпажкой шашлыка. используется паста спагетти.",
      is_kids_menu: false,
      category: "паста",
      id: 44,
    },
    {
      name: "карбонара без кое-каких сливок",
      portion_size: "290",
      unit: "гр",
      price: 340,
      image: "",
      description:
        "соус приготовлен на базе желтков, белого вина и сыра пармезан с беконом. используется паста спагетти.",
      is_kids_menu: false,
      category: "паста",
      id: 45,
    },
    {
      name: "картофель фри",
      portion_size: "150",
      unit: "гр",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "гарниры",
      id: 46,
    },
    {
      name: "картофельное пюре",
      portion_size: "150",
      unit: "гр",
      price: 170,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "гарниры",
      id: 47,
    },
    {
      name: "овощи на пару",
      portion_size: "150",
      unit: "гр",
      price: 120,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "гарниры",
      id: 48,
    },
    {
      name: "овощи на гриле",
      portion_size: "150",
      unit: "гр",
      price: 160,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "гарниры",
      id: 49,
    },
    {
      name: "рис отварной",
      portion_size: "150",
      unit: "гр",
      price: 100,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "гарниры",
      id: 50,
    },
    {
      name: "манговый медовик",
      portion_size: "150",
      unit: "гр",
      price: 220,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "десерты",
      id: 51,
    },
    {
      name: "наполеон малиновый",
      portion_size: "150",
      unit: "гр",
      price: 220,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "десерты",
      id: 52,
    },
    {
      name: "чизкейк с ягодным соусом",
      portion_size: "150",
      unit: "гр",
      price: 280,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "десерты",
      id: 53,
    },
    {
      name: "шоколадный чиз",
      portion_size: "150",
      unit: "гр",
      price: 285,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "десерты",
      id: 54,
    },
    {
      name: "эспрессо",
      portion_size: "38",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 55,
    },
    {
      name: "американо",
      portion_size: "300",
      unit: "мл",
      price: 120,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 56,
    },
    {
      name: "капучино",
      portion_size: "300",
      unit: "мл",
      price: 140,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 57,
    },
    {
      name: "флет уайт",
      portion_size: "300",
      unit: "мл",
      price: 160,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 58,
    },
    {
      name: "раф",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 59,
    },
    {
      name: "капучино с лавандой",
      portion_size: "300",
      unit: "мл",
      price: 160,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 60,
    },
    {
      name: "кофе на банановом",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 61,
    },
    {
      name: "кофе на кокосовом",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 62,
    },
    {
      name: "капучино с малиной",
      portion_size: "300",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 63,
    },
    {
      name: "банановый фраппе",
      portion_size: "350",
      unit: "мл",
      price: 170,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "кофе",
      id: 64,
    },
    {
      name: "черный",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 65,
    },
    {
      name: "зеленый сенча",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 66,
    },
    {
      name: "зеленый дыня карамель",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 67,
    },
    {
      name: "пуэр юннань",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 68,
    },
    {
      name: "улун молочный",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 69,
    },
    {
      name: "дерзкий фрукт",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 70,
    },
    {
      name: "черный черная смородина",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 71,
    },
    {
      name: "черный эрл грей",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 72,
    },
    {
      name: "черный барбарисовый",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 73,
    },
    {
      name: "травяной лимон с имбирем",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 74,
    },
    {
      name: "травяной мятный каркаде",
      portion_size: "600",
      unit: "мл",
      price: 150,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "чай",
      id: 75,
    },
    {
      name: "персик-розмарин",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "фирменный чай",
      id: 76,
    },
    {
      name: "лемонграсс-киви",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "фирменный чай",
      id: 77,
    },
    {
      name: "черная смородина-каркаде",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "фирменный чай",
      id: 78,
    },
    {
      name: "облепиха-глинтвейн",
      portion_size: "600",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "фирменный чай",
      id: 79,
    },
    {
      name: "бон аква газ",
      portion_size: "330",
      unit: "мл",
      price: 120,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 80,
    },
    {
      name: "бон аква негаз",
      portion_size: "330",
      unit: "мл",
      price: 120,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 81,
    },
    {
      name: "рич ананас",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 82,
    },
    {
      name: "рич апельсин",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 83,
    },
    {
      name: "рич яблоко",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 84,
    },
    {
      name: "рич вишня",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 85,
    },
    {
      name: "рич персик",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 86,
    },
    {
      name: "рич томат",
      portion_size: "200",
      unit: "мл",
      price: 180,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 87,
    },
    {
      name: "добрый кола",
      portion_size: "330",
      unit: "мл",
      price: 140,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "напитки",
      id: 88,
    },
    {
      name: "классический",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 89,
    },
    {
      name: "тархун",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 90,
    },
    {
      name: "огурец-мята",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 91,
    },
    {
      name: "маракуя-матча",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 92,
    },
    {
      name: "малина-клубника-огурец",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 93,
    },
    {
      name: "груша-базилик",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 94,
    },
    {
      name: "облепиха-тархун",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 95,
    },
    {
      name: "груша-щавель",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 96,
    },
    {
      name: "грейпфрут-бабл гам",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 97,
    },
    {
      name: "лаванда-малина",
      portion_size: "1000",
      unit: "мл",
      price: 250,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 98,
    },
    {
      name: "ананас-миндаль",
      portion_size: "1000",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "лимонады",
      id: 99,
    },
    {
      name: "ягодный лемонграсс",
      portion_size: "250",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "морсы",
      id: 100,
    },
    {
      name: "клюква-имбирь",
      portion_size: "250",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "морсы",
      id: 101,
    },
    {
      name: "облепиха-вишня",
      portion_size: "250",
      unit: "мл",
      price: 80,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "морсы",
      id: 102,
    },
    {
      name: "киви",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "милкшейки",
      id: 103,
    },
    {
      name: "банановый с шоколадом",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "милкшейки",
      id: 104,
    },
    {
      name: "классика",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "милкшейки",
      id: 105,
    },
    {
      name: "карамельный",
      portion_size: "300",
      unit: "мл",
      price: 210,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "милкшейки",
      id: 106,
    },
  ];

  const menuAlco = [
    {
      name: "чело э терра с.п.а. шардоне",
      portion_size: "750",
      unit: "мл",
      price: 1850,
      image: "",
      description: "полусухое",
      is_kids_menu: false,
      category: "белые вина",
      id: 107,
    },
    {
      name: "кавиро агрикола пино гриджио",
      portion_size: "750",
      unit: "мл",
      price: 2100,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "белые вина",
      id: 108,
    },
    {
      name: "рислинг бекштайнер",
      portion_size: "750",
      unit: "мл",
      price: 2250,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "белые вина",
      id: 109,
    },
    {
      name: "арко бэй мальборо совиньон блан",
      portion_size: "750",
      unit: "мл",
      price: 1600,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "белые вина",
      id: 110,
    },
    {
      name: "ривер рут гевюрцтраминер ",
      portion_size: "750",
      unit: "мл",
      price: 2950,
      image: "",
      description: "полусладкое",
      is_kids_menu: false,
      category: "белые вина",
      id: 111,
    },
    {
      name: "винью верде альту лима ",
      portion_size: "750",
      unit: "мл",
      price: 1850,
      image: "",
      description: "полусухое",
      is_kids_menu: false,
      category: "белые вина",
      id: 112,
    },
    {
      name: "ханс баер рислинг",
      portion_size: "750",
      unit: "мл",
      price: 2000,
      image: "",
      description: "ба",
      is_kids_menu: false,
      category: "белые вина",
      id: 113,
    },
    {
      name: "кампо делия ла манча темпранильо",
      portion_size: "750",
      unit: "мл",
      price: 1750,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "красные вина",
      id: 114,
    },
    {
      name: "гато негро семисвит ред каберне совиньон ",
      portion_size: "750",
      unit: "мл",
      price: 2450,
      image: "",
      description: "полусладкое",
      is_kids_menu: false,
      category: "красные вина",
      id: 115,
    },
    {
      name: "трапиче виньярдс мальбек ",
      portion_size: "750",
      unit: "мл",
      price: 2200,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "красные вина",
      id: 116,
    },
    {
      name: "кукабара каберне совиньон ",
      portion_size: "750",
      unit: "мл",
      price: 1490,
      image: "",
      description: "полусладкое",
      is_kids_menu: false,
      category: "красные вина",
      id: 117,
    },
    {
      name: "торнберрис зинфандель розе",
      portion_size: "750",
      unit: "мл",
      price: 1950,
      image: "",
      description: "полусладкое",
      is_kids_menu: false,
      category: "розовые вина",
      id: 118,
    },
    {
      name: "вайнкеллерай ленц мозер цвайгельт розе",
      portion_size: "750",
      unit: "мл",
      price: 1950,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "розовые вина",
      id: 119,
    },
    {
      name: "ханс баер пино нуар",
      portion_size: "750",
      unit: "мл",
      price: 2000,
      image: "",
      description: "ба",
      is_kids_menu: false,
      category: "розовые вина",
      id: 120,
    },
    {
      name: "павао розе",
      portion_size: "750",
      unit: "мл",
      price: 1600,
      image: "",
      description: "полусухое",
      is_kids_menu: false,
      category: "розовые вина",
      id: 121,
    },
    {
      name: "прозекко",
      portion_size: "750",
      unit: "мл",
      price: 3200,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "игристые вина",
      id: 122,
    },
    {
      name: "кава винарт брют ",
      portion_size: "750",
      unit: "мл",
      price: 2200,
      image: "",
      description: "сухое",
      is_kids_menu: false,
      category: "игристые вина",
      id: 123,
    },
    {
      name: "гаэтано асти",
      portion_size: "750",
      unit: "мл",
      price: 1950,
      image: "",
      description: "сладкое",
      is_kids_menu: false,
      category: "игристые вина",
      id: 124,
    },
    {
      name: "пти розе",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      description: "белое, сухое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 125,
    },
    {
      name: "гаэтано пино гриджио",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      description: "белое, полусухое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 126,
    },
    {
      name: "фалькегбург муска",
      portion_size: "150",
      unit: "мл",
      price: 340,
      image: "",
      description: "белое, полусладкое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 127,
    },
    {
      name: "пти розе",
      portion_size: "150",
      unit: "мл",
      price: 285,
      image: "",
      description: "красное, сухое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 128,
    },
    {
      name: "гаэтано санджовез",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      description: "красное, полусухое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 129,
    },
    {
      name: "каса нери темпранильо",
      portion_size: "150",
      unit: "мл",
      price: 285,
      image: "",
      description: "красное, полусладкое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 130,
    },
    {
      name: "высокий берег ординарное",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      description: "розовое, сухое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 131,
    },
    {
      name: "гаэтано прозекко",
      portion_size: "150",
      unit: "мл",
      price: 295,
      image: "",
      description: "игристое, сухое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 132,
    },
    {
      name: "гаэтано прозекко",
      portion_size: "200",
      unit: "мл",
      price: 420,
      image: "",
      description: "игристое, сухое",
      is_kids_menu: false,
      category: "вина по бокалам",
      id: 133,
    },
    {
      name: "крюгер дункель",
      portion_size: "500",
      unit: "мл",
      price: 250,
      image: "",
      description: "светлое",
      is_kids_menu: false,
      category: "пиво",
      id: 134,
    },
    {
      name: "крюгер дункель",
      portion_size: "500",
      unit: "мл",
      price: 250,
      image: "",
      description: "темное",
      is_kids_menu: false,
      category: "пиво",
      id: 135,
    },
    {
      name: "харвестер",
      portion_size: "500",
      unit: "мл",
      price: 250,
      image: "",
      description: "светлое",
      is_kids_menu: false,
      category: "пиво",
      id: 136,
    },
    {
      name: "бакалар",
      portion_size: "330",
      unit: "мл",
      price: 295,
      image: "",
      description: "светлое, б/а",
      is_kids_menu: false,
      category: "пиво",
      id: 137,
    },
    {
      name: "аркоброй мозер лизель",
      portion_size: "500",
      unit: "мл",
      price: 490,
      image: "",
      description: "светлое",
      is_kids_menu: false,
      category: "пиво",
      id: 138,
    },
    {
      name: "либенвайс хефе-вайсбир",
      portion_size: "500",
      unit: "мл",
      price: 480,
      image: "",
      description: "светлое",
      is_kids_menu: false,
      category: "пиво",
      id: 139,
    },
    {
      name: "черновар",
      portion_size: "500",
      unit: "мл",
      price: 480,
      image: "темное",
      description: "",
      is_kids_menu: false,
      category: "пиво",
      id: 140,
    },
    {
      name: "апероль сприц",
      portion_size: "400",
      unit: "мл",
      price: 310,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 141,
    },
    {
      name: "мимоза",
      portion_size: "300",
      unit: "мл",
      price: 280,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 142,
    },
    {
      name: "кир рояль",
      portion_size: "300",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 143,
    },
    {
      name: "клубничный сауэр",
      portion_size: "300",
      unit: "мл",
      price: 290,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 144,
    },
    {
      name: "черносмородиновый сауэр",
      portion_size: "300",
      unit: "мл",
      price: 310,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 145,
    },
    {
      name: "мандарин рояль",
      portion_size: "350",
      unit: "мл",
      price: 310,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 146,
    },
    {
      name: "фиеро тоник",
      portion_size: "350",
      unit: "мл",
      price: 310,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 147,
    },
    {
      name: "беллини",
      portion_size: "350",
      unit: "мл",
      price: 310,
      image: "",
      description: "",
      is_kids_menu: false,
      category: "коктейли",
      id: 148,
    },
    {
      name: "персиковый",
      portion_size: "300",
      unit: "мл",
      price: 220,
      image: "",
      description: "персиковый сироп, пюре манго, сок лимона, хугарден 0%",
      is_kids_menu: false,
      category: "коктейли (безалкогольные)",
      id: 149,
    },
    {
      name: "грушевый",
      portion_size: "300",
      unit: "мл",
      price: 220,
      image: "",
      description:
        "кленовый сироп, грушевый сироп, сок лимона, вино б/а, хугарден 0%",
      is_kids_menu: false,
      category: "коктейли (безалкогольные)",
      id: 150,
    },
    {
      name: "апероль",
      portion_size: "300",
      unit: "мл",
      price: 200,
      image: "",
      description: "сироп апероль, вино ба",
      is_kids_menu: false,
      category: "коктейли (безалкогольные)",
      id: 151,
    },
    {
      name: "мохито",
      portion_size: "300",
      unit: "мл",
      price: 200,
      image: "",
      description: "сахарный сироп, лайм, мята, содовая",
      is_kids_menu: false,
      category: "коктейли (безалкогольные)",
      id: 152,
    },
    {
      name: "мандарин-тархун",
      portion_size: "300",
      unit: "мл",
      price: 190,
      image: "",
      description: "сахарный сироп, лайм, мята, содовая",
      is_kids_menu: false,
      category: "коктейли (безалкогольные)",
      id: 153,
    },
    {
      name: "курасао",
      portion_size: "300",
      unit: "мл",
      price: 200,
      image: "",
      description:
        "сок апельсина, сок ананаса, сок яблока, сироп блю курасао, сок лимона",
      is_kids_menu: false,
      category: "коктейли (безалкогольные)",
      id: 154,
    },
    {
      name: "глинтвейн",
      portion_size: "300",
      unit: "мл",
      price: 230,
      image: "",
      description: "сок вишня/яблоко, апельсин, лимон, мед, яблоко, специи",
      is_kids_menu: false,
      category: "коктейли (безалкогольные)",
      id: 155,
    },
  ];

  return {
    menu,
    menuAlco,
  };
}
